// Code generated by mss-protoc-gen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/entity"
)

// WorkLocationDTO は WorkLocation エンティティをクライアントへ返すための JSON シリアライズ型。
// json タグはここで一元管理する。entity 側は GORM タグのみ持つ。
type WorkLocationDTO struct {
	Date     string `json:"date"`
	Location string `json:"location"`
}

// FromWorkLocation は entity.WorkLocation を WorkLocationDTO に変換する。
// nil を渡したら nil を返す。
func FromWorkLocation(e *entity.WorkLocation) *WorkLocationDTO {
	if e == nil {
		return nil
	}
	return &WorkLocationDTO{
		Date:     e.Date,
		Location: e.Location,
	}
}

// FromWorkLocations は []*entity.WorkLocation を []*WorkLocationDTO に変換する。
func FromWorkLocations(es []*entity.WorkLocation) []*WorkLocationDTO {
	out := make([]*WorkLocationDTO, 0, len(es))
	for _, e := range es {
		out = append(out, FromWorkLocation(e))
	}
	return out
}

var _ = time.Time{}
