// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"

	"{{.ImportEntity}}"
	"{{.ImportRepository}}"
)

// Redis への保存形式（docs/patterns/infra-swap.md: string に JSON エンコード）。
// 本体は {{.Plural}}:rec:<pk>、@unique の副次インデックスは {{.Plural}}:idx:<field>:<value> → pk。
type redis{{.Name}}Record struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} `json:"{{.SnakeName}}"`
{{- end}}
}

func to{{.Name}}Record(e *entity.{{.Name}}) redis{{.Name}}Record {
	return redis{{.Name}}Record{
{{- range .Fields}}
		{{.GoName}}: e.{{.GoName}},
{{- end}}
	}
}

func (r redis{{.Name}}Record) toEntity() *entity.{{.Name}} {
	return &entity.{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: r.{{.GoName}},
{{- end}}
	}
}

type redis{{.Name}}Repository struct {
	client redis.UniversalClient
}

func NewRedis{{.Name}}Repository(client redis.UniversalClient) repository.{{.Name}}Repository {
	return &redis{{.Name}}Repository{client: client}
}

var _ repository.{{.Name}}Repository = (*redis{{.Name}}Repository)(nil)
var _ = time.Time{}

const {{.LowerFirst}}KeyPrefix = "{{.Plural}}:rec:"

func {{.LowerFirst}}Key(pk {{.PKField.GoType}}) string { return {{.LowerFirst}}KeyPrefix + fmt.Sprint(pk) }

func {{.LowerFirst}}IndexKeys(e *entity.{{.Name}}) []string {
	return []string{
{{- range .UniqueFieldsNonPK}}
		"{{$.Plural}}:idx:{{.SnakeName}}:" + fmt.Sprint(e.{{.GoName}}),
{{- end}}
	}
}

func (r *redis{{.Name}}Repository) get(ctx context.Context, key string) (*entity.{{.Name}}, error) {
	raw, err := r.client.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rec redis{{.Name}}Record
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("decode %s: %w", key, err)
	}
	return rec.toEntity(), nil
}

func (r *redis{{.Name}}Repository) SelectAll(ctx context.Context) ([]*entity.{{.Name}}, error) {
	var keys []string
	iter := r.client.Scan(ctx, 0, {{.LowerFirst}}KeyPrefix+"*", 500).Iterator()
	for iter.Next(ctx) {
		keys = append(keys, iter.Val())
	}
	if err := iter.Err(); err != nil {
		return nil, err
	}
	out := make([]*entity.{{.Name}}, 0, len(keys))
	for start := 0; start < len(keys); start += 500 {
		end := min(start+500, len(keys))
		vals, err := r.client.MGet(ctx, keys[start:end]...).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			s, ok := v.(string)
			if !ok {
				continue // SCAN と MGET の間に消えた
			}
			var rec redis{{.Name}}Record
			if err := json.Unmarshal([]byte(s), &rec); err != nil {
				return nil, fmt.Errorf("decode %s: %w", keys[start+i], err)
			}
			out = append(out, rec.toEntity())
		}
	}
	return out, nil
}

func (r *redis{{.Name}}Repository) SelectByPK(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) (*entity.{{.Name}}, error) {
	return r.get(ctx, {{.LowerFirst}}Key({{.PKField.ParamName}}))
}
{{range .UniqueFieldsNonPK}}
func (r *redis{{$.Name}}Repository) SelectBy{{.GoName}}(ctx context.Context, {{.ParamName}} {{.GoType}}) (*entity.{{$.Name}}, error) {
	pk, err := r.client.Get(ctx, "{{$.Plural}}:idx:{{.SnakeName}}:"+fmt.Sprint({{.ParamName}})).Result()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.get(ctx, {{$.LowerFirst}}KeyPrefix+pk)
}
{{end}}
func (r *redis{{.Name}}Repository) Insert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	raw, err := json.Marshal(to{{.Name}}Record({{.LowerFirst}}))
	if err != nil {
		return err
	}
	key := {{.LowerFirst}}Key({{.LowerFirst}}.{{.PKField.GoName}})
	ok, err := r.client.SetNX(ctx, key, raw, 0).Result()
	if err != nil {
		return err
	}
	if !ok {
		return repository.Err{{.Name}}AlreadyExists
	}
	pk := fmt.Sprint({{.LowerFirst}}.{{.PKField.GoName}})
	var claimed []string
	for _, idx := range {{.LowerFirst}}IndexKeys({{.LowerFirst}}) {
		ok, err := r.client.SetNX(ctx, idx, pk, 0).Result()
		if err != nil || !ok {
			// 一意制約違反: 先に書いた分を戻す
			r.client.Del(ctx, append(claimed, key)...)
			if err != nil {
				return err
			}
			return repository.Err{{.Name}}AlreadyExists
		}
		claimed = append(claimed, idx)
	}
	return nil
}

func (r *redis{{.Name}}Repository) BulkInsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	for _, e := range {{.Plural}} {
		if err := r.Insert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redis{{.Name}}Repository) Upsert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	prev, err := r.SelectByPK(ctx, {{.LowerFirst}}.{{.PKField.GoName}})
	if err != nil {
		return err
	}
	raw, err := json.Marshal(to{{.Name}}Record({{.LowerFirst}}))
	if err != nil {
		return err
	}
	pk := fmt.Sprint({{.LowerFirst}}.{{.PKField.GoName}})
	pipe := r.client.TxPipeline()
	if prev != nil {
		for _, idx := range {{.LowerFirst}}IndexKeys(prev) {
			pipe.Del(ctx, idx)
		}
	}
	pipe.Set(ctx, {{.LowerFirst}}Key({{.LowerFirst}}.{{.PKField.GoName}}), raw, 0)
	for _, idx := range {{.LowerFirst}}IndexKeys({{.LowerFirst}}) {
		pipe.Set(ctx, idx, pk, 0)
	}
	_, err = pipe.Exec(ctx)
	return err
}

func (r *redis{{.Name}}Repository) BulkUpsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	for _, e := range {{.Plural}} {
		if err := r.Upsert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redis{{.Name}}Repository) Update(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	n, err := r.client.Exists(ctx, {{.LowerFirst}}Key({{.LowerFirst}}.{{.PKField.GoName}})).Result()
	if err != nil {
		return err
	}
	if n == 0 {
		return repository.Err{{.Name}}NotFound
	}
	return r.Upsert(ctx, {{.LowerFirst}})
}

func (r *redis{{.Name}}Repository) Delete(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) error {
	prev, err := r.SelectByPK(ctx, {{.PKField.ParamName}})
	if err != nil {
		return err
	}
	if prev == nil {
		return repository.Err{{.Name}}NotFound
	}
	return r.client.Del(ctx, append({{.LowerFirst}}IndexKeys(prev), {{.LowerFirst}}Key({{.PKField.ParamName}}))...).Err()
}

func (r *redis{{.Name}}Repository) BulkDelete(ctx context.Context, {{.PKField.ParamName}}s []{{.PKField.GoType}}) error {
	missing := false
	for _, pk := range {{.PKField.ParamName}}s {
		if err := r.Delete(ctx, pk); err != nil {
			if errors.Is(err, repository.Err{{.Name}}NotFound) {
				missing = true
				continue
			}
			return err
		}
	}
	if missing {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *redis{{.Name}}Repository) DeleteAll(ctx context.Context) error {
	for _, pattern := range []string{ {{.LowerFirst}}KeyPrefix + "*", "{{.Plural}}:idx:*"} {
		iter := r.client.Scan(ctx, 0, pattern, 500).Iterator()
		var keys []string
		for iter.Next(ctx) {
			keys = append(keys, iter.Val())
		}
		if err := iter.Err(); err != nil {
			return err
		}
		if len(keys) > 0 {
			if err := r.client.Del(ctx, keys...).Err(); err != nil {
				return err
			}
		}
	}
	return nil
}
{{- if .PagingField}}

// SelectByCursor は KVS に順序がないため全件を読み、{{.PagingField.SnakeName}} の昇順で切り出す。
func (r *redis{{.Name}}Repository) SelectByCursor(ctx context.Context, limit int, after *{{.PagingField.GoType}}) ([]*entity.{{.Name}}, error) {
	all, err := r.SelectAll(ctx)
	if err != nil {
		return nil, err
	}
	sort.Slice(all, func(i, j int) bool { return all[i].{{.PagingField.GoName}} < all[j].{{.PagingField.GoName}} })
	out := make([]*entity.{{.Name}}, 0, limit)
	for _, e := range all {
		if after != nil && !(e.{{.PagingField.GoName}} > *after) {
			continue
		}
		out = append(out, e)
		if len(out) == limit {
			break
		}
	}
	return out, nil
}
{{- else}}

var _ = sort.Strings
{{- end}}
