// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/inquiry/v1/inquiryv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/inquiry/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/inquiry/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	InquiryService *handler.InquiryHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	inquiryUsecase usecase.InquiryUsecase,
) *Handlers {
	return &Handlers{
		InquiryService: handler.NewInquiryHandler(inquiryUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(inquiryv1connect.NewInquiryServiceHandler(h.InquiryService, opts...))
}
