# Workload Identity: この KSA を GCP の SA（taramanji-app@PROJECT_ID.iam.gserviceaccount.com）に紐づける
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taramanji-app
  annotations:
    iam.gke.io/gcp-service-account: taramanji-app@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
