// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

var ErrCalendarAccountNotFound = errors.New("calendar_account not found")
var ErrCalendarAccountAlreadyExists = errors.New("calendar_account already exists")

type CalendarAccountRepository interface {
	SelectAll(ctx context.Context) ([]*entity.CalendarAccount, error)
	SelectByPK(ctx context.Context, calendarId string) (*entity.CalendarAccount, error)
	Insert(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	BulkInsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error
	Upsert(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	BulkUpsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error
	Update(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	Delete(ctx context.Context, calendarId string) error
	BulkDelete(ctx context.Context, calendarIds []string) error
	DeleteAll(ctx context.Context) error
}
