// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

var ErrSyncSettingNotFound = errors.New("sync_setting not found")
var ErrSyncSettingAlreadyExists = errors.New("sync_setting already exists")

type SyncSettingRepository interface {
	SelectAll(ctx context.Context) ([]*entity.SyncSetting, error)
	SelectByPK(ctx context.Context, id string) (*entity.SyncSetting, error)
	Insert(ctx context.Context, syncSetting *entity.SyncSetting) error
	BulkInsert(ctx context.Context, syncSettings []*entity.SyncSetting) error
	Upsert(ctx context.Context, syncSetting *entity.SyncSetting) error
	BulkUpsert(ctx context.Context, syncSettings []*entity.SyncSetting) error
	Update(ctx context.Context, syncSetting *entity.SyncSetting) error
	Delete(ctx context.Context, id string) error
	BulkDelete(ctx context.Context, ids []string) error
	DeleteAll(ctx context.Context) error
}
