// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

var ErrSyncMirrorNotFound = errors.New("sync_mirror not found")
var ErrSyncMirrorAlreadyExists = errors.New("sync_mirror already exists")

type SyncMirrorRepository interface {
	SelectAll(ctx context.Context) ([]*entity.SyncMirror, error)
	SelectByPK(ctx context.Context, key string) (*entity.SyncMirror, error)
	Insert(ctx context.Context, syncMirror *entity.SyncMirror) error
	BulkInsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error
	Upsert(ctx context.Context, syncMirror *entity.SyncMirror) error
	BulkUpsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error
	Update(ctx context.Context, syncMirror *entity.SyncMirror) error
	Delete(ctx context.Context, key string) error
	BulkDelete(ctx context.Context, keys []string) error
	DeleteAll(ctx context.Context) error
}
