// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"

	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/entity"
)

var ErrWorkLocationNotFound = errors.New("work_location not found")
var ErrWorkLocationAlreadyExists = errors.New("work_location already exists")

type WorkLocationRepository interface {
	SelectAll(ctx context.Context) ([]*entity.WorkLocation, error)
	SelectByPK(ctx context.Context, date string) (*entity.WorkLocation, error)
	Insert(ctx context.Context, workLocation *entity.WorkLocation) error
	BulkInsert(ctx context.Context, workLocations []*entity.WorkLocation) error
	Upsert(ctx context.Context, workLocation *entity.WorkLocation) error
	BulkUpsert(ctx context.Context, workLocations []*entity.WorkLocation) error
	Update(ctx context.Context, workLocation *entity.WorkLocation) error
	Delete(ctx context.Context, date string) error
	BulkDelete(ctx context.Context, dates []string) error
	DeleteAll(ctx context.Context) error
}
