// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	worklocationv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/worklocation/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/worklocation/v1/worklocationv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// WorkLocationHandler は WorkLocationService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type WorkLocationHandler struct {
	usecase usecase.WorkLocationUsecase
}

func NewWorkLocationHandler(uc usecase.WorkLocationUsecase) *WorkLocationHandler {
	return &WorkLocationHandler{usecase: uc}
}

var _ worklocationv1connect.WorkLocationServiceHandler = (*WorkLocationHandler)(nil)

func (h *WorkLocationHandler) ListWorkLocations(ctx context.Context, req *connect.Request[worklocationv1.ListWorkLocationsRequest]) (*connect.Response[worklocationv1.ListWorkLocationsResponse], error) {
	out, err := h.usecase.ListWorkLocations(ctx, usecase.ListWorkLocationsInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&worklocationv1.ListWorkLocationsResponse{Locations: out.Locations}), nil
}

func (h *WorkLocationHandler) SetWorkLocations(ctx context.Context, req *connect.Request[worklocationv1.SetWorkLocationsRequest]) (*connect.Response[worklocationv1.SetWorkLocationsResponse], error) {
	out, err := h.usecase.SetWorkLocations(ctx, usecase.SetWorkLocationsInput{
		Dates:    req.Msg.GetDates(),
		Location: req.Msg.GetLocation(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&worklocationv1.SetWorkLocationsResponse{Count: out.Count}), nil
}

func (h *WorkLocationHandler) DeleteWorkLocation(ctx context.Context, req *connect.Request[worklocationv1.DeleteWorkLocationRequest]) (*connect.Response[worklocationv1.DeleteWorkLocationResponse], error) {
	if err := h.usecase.DeleteWorkLocation(ctx, usecase.DeleteWorkLocationInput{
		Date: req.Msg.GetDate(),
	}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&worklocationv1.DeleteWorkLocationResponse{}), nil
}

func (h *WorkLocationHandler) GetWorkLocation(ctx context.Context, req *connect.Request[worklocationv1.GetWorkLocationRequest]) (*connect.Response[worklocationv1.GetWorkLocationResponse], error) {
	out, err := h.usecase.GetWorkLocation(ctx, usecase.GetWorkLocationInput{
		Date: req.Msg.GetDate(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&worklocationv1.GetWorkLocationResponse{Location: out.Location}), nil
}
