apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
  - namespace.yaml
  - ../redis
  - app.yaml
secretGenerator:
  - name: portfolio-secrets
    envs:
      - secret.env
images:
  - name: taramanji-web
    newTag: local
