// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type CreateReservationInput struct {
	Year               int32
	Month              int32
	Day                int32
	Weekday            string
	Start              *ClockTime
	End                *ClockTime
	Name               string
	Email              string
	Purpose            string
	ContactMethod      string
	DiscordName        string
	DiscordServer      string
	SlackName          string
	SlackWorkspace     string
	OtherNote          string
	OfflinePlaceLink   string
	OfflinePlaceName   string
	OfflinePlaceDetail string
	MeetingNote        string
	Location           string
}

type GetReservationInput struct {
	EventID string
}

type CancelReservationInput struct {
	EventID string
}

type GetBusyInput struct {
	WeekStartIso string
	NoBuffer     bool
	Debug        bool
}

type ResolveMapsUrlInput struct {
	URL string
}

type ReserveResearchInput struct{}

type ListIcalSourcesInput struct {
	WeekStartIso string
}

type CreateReservationOutput struct {
	EventID  string `json:"event_id"`
	HtmlLink string `json:"html_link"`
	MeetLink string `json:"meet_link"`
	Invited  bool   `json:"invited"`
	Note     string `json:"note"`
	Status   int32  `json:"status"`
}

type GetReservationOutput struct {
	EventID  string `json:"event_id"`
	HtmlLink string `json:"html_link"`
	MeetLink string `json:"meet_link"`
}

type CancelReservationOutput struct {
	Deleted    bool   `json:"deleted"`
	Suggestion string `json:"suggestion"`
	Status     int32  `json:"status"`
}

type GetBusyOutput struct {
	Busy        []*Interval         `json:"busy"`
	SourceCount int32               `json:"source_count"`
	Sources     []*IcalSourceStatus `json:"sources"`
}

type ResolveMapsUrlOutput struct {
	Name     string `json:"name"`
	FinalURL string `json:"final_url"`
	Error    string `json:"error"`
}

type ListIcalSourcesOutput struct {
	Sources   []*IcalSourceStatus `json:"sources"`
	Events    []*IcalEvent        `json:"events"`
	WeekStart string              `json:"week_start"`
	WeekEnd   string              `json:"week_end"`
}

type ClockTime struct {
	Hour   int32 `json:"hour"`
	Minute int32 `json:"minute"`
}

type IcalEvent struct {
	Start     string `json:"start"`
	End       string `json:"end"`
	Summary   string `json:"summary"`
	Source    string `json:"source"`
	SourceURL string `json:"source_url"`
}

type IcalSourceStatus struct {
	URL        string `json:"url"`
	Name       string `json:"name"`
	Ok         bool   `json:"ok"`
	Status     int32  `json:"status"`
	Length     int32  `json:"length"`
	EventCount int32  `json:"event_count"`
}

type Interval struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

// ReservationUsecase は ReservationService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type ReservationUsecase interface {
	CreateReservation(ctx context.Context, input CreateReservationInput) (*CreateReservationOutput, error)
	GetReservation(ctx context.Context, input GetReservationInput) (*GetReservationOutput, error)
	CancelReservation(ctx context.Context, input CancelReservationInput) (*CancelReservationOutput, error)
	GetBusy(ctx context.Context, input GetBusyInput) (*GetBusyOutput, error)
	ResolveMapsUrl(ctx context.Context, input ResolveMapsUrlInput) (*ResolveMapsUrlOutput, error)
	ReserveResearch(ctx context.Context, input ReserveResearchInput) error
	ListIcalSources(ctx context.Context, input ListIcalSourcesInput) (*ListIcalSourcesOutput, error)
}
