// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	{{.Connect.PbPkg}} "{{.Connect.PbImport}}"
	"{{.Connect.ConnectImport}}"
{{- if .Connect.UsesDTO}}
	"{{.ImportDTO}}"
{{- end}}
	"{{.ImportUsecase}}"
	"{{.ImportErrs}}"
)

// {{.HandlerTypeName}} は {{.ServiceName}} の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type {{.HandlerTypeName}} struct {
	usecase usecase.{{.UsecaseTypeName}}
}

func New{{.HandlerTypeName}}(uc usecase.{{.UsecaseTypeName}}) *{{.HandlerTypeName}} {
	return &{{.HandlerTypeName}}{usecase: uc}
}

var _ {{.Connect.ConnectPkg}}.{{.Connect.ServiceGoName}}Handler = (*{{.HandlerTypeName}})(nil)
{{range .Connect.Methods}}
func (h *{{$.HandlerTypeName}}) {{.Name}}(ctx context.Context, req *connect.Request[{{.ReqType}}]) (*connect.Response[{{.ResType}}], error) {
{{- if .ReturnsEmpty}}
	if err := h.usecase.{{.Name}}(ctx, usecase.{{.Name}}Input{
{{- range .InputAssigns}}
		{{.}}
{{- end}}
	}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
{{- else}}
	out, err := h.usecase.{{.Name}}(ctx, usecase.{{.Name}}Input{
{{- range .InputAssigns}}
		{{.}}
{{- end}}
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
{{- end}}
	return connect.NewResponse({{.Response}}), nil
}
{{end}}
{{- range .Connect.Converters}}
{{.}}
{{end}}
