// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	calendarsyncv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/calendarsync/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/calendarsync/v1/calendarsyncv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// CalendarSyncHandler は CalendarSyncService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type CalendarSyncHandler struct {
	usecase usecase.CalendarSyncUsecase
}

func NewCalendarSyncHandler(uc usecase.CalendarSyncUsecase) *CalendarSyncHandler {
	return &CalendarSyncHandler{usecase: uc}
}

var _ calendarsyncv1connect.CalendarSyncServiceHandler = (*CalendarSyncHandler)(nil)

func (h *CalendarSyncHandler) GetStatus(ctx context.Context, req *connect.Request[calendarsyncv1.GetStatusRequest]) (*connect.Response[calendarsyncv1.GetStatusResponse], error) {
	out, err := h.usecase.GetStatus(ctx, usecase.GetStatusInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&calendarsyncv1.GetStatusResponse{Master: out.Master, Accounts: func(l []*usecase.AccountView) []*calendarsyncv1.AccountView {
		if l == nil {
			return nil
		}
		out := make([]*calendarsyncv1.AccountView, 0, len(l))
		for _, v := range l {
			out = append(out, calendarSyncAccountViewToPb(v))
		}
		return out
	}(out.Accounts), LastRun: calendarSyncLastRunToPb(out.LastRun)}), nil
}

func (h *CalendarSyncHandler) RunSync(ctx context.Context, req *connect.Request[calendarsyncv1.RunSyncRequest]) (*connect.Response[calendarsyncv1.RunSyncResponse], error) {
	out, err := h.usecase.RunSync(ctx, usecase.RunSyncInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&calendarsyncv1.RunSyncResponse{Run: calendarSyncLastRunToPb(out.Run), Skipped: out.Skipped}), nil
}

func (h *CalendarSyncHandler) UpdateSettings(ctx context.Context, req *connect.Request[calendarsyncv1.UpdateSettingsRequest]) (*connect.Response[calendarsyncv1.UpdateSettingsResponse], error) {
	if err := h.usecase.UpdateSettings(ctx, usecase.UpdateSettingsInput{
		SetMaster:         req.Msg.GetSetMaster(),
		Master:            req.Msg.GetMaster(),
		PrivateCalendarID: req.Msg.GetPrivateCalendarId(),
		PrivateValue:      req.Msg.GetPrivateValue(),
	}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&calendarsyncv1.UpdateSettingsResponse{}), nil
}

func (h *CalendarSyncHandler) Disconnect(ctx context.Context, req *connect.Request[calendarsyncv1.DisconnectRequest]) (*connect.Response[calendarsyncv1.DisconnectResponse], error) {
	out, err := h.usecase.Disconnect(ctx, usecase.DisconnectInput{
		CalendarID: req.Msg.GetCalendarId(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&calendarsyncv1.DisconnectResponse{Deleted: out.Deleted, Failed: out.Failed}), nil
}

func calendarSyncPbToAccountView(p *calendarsyncv1.AccountView) *usecase.AccountView {
	if p == nil {
		return nil
	}
	return &usecase.AccountView{
		CalendarID:  p.GetCalendarId(),
		Private:     p.GetPrivate(),
		ConnectedAt: p.GetConnectedAt(),
	}
}

func calendarSyncAccountViewToPb(u *usecase.AccountView) *calendarsyncv1.AccountView {
	if u == nil {
		return nil
	}
	return &calendarsyncv1.AccountView{
		CalendarId:  u.CalendarID,
		Private:     u.Private,
		ConnectedAt: u.ConnectedAt,
	}
}

func calendarSyncPbToSyncError(p *calendarsyncv1.SyncError) *usecase.SyncError {
	if p == nil {
		return nil
	}
	return &usecase.SyncError{
		CalendarID: p.GetCalendarId(),
		Error:      p.GetError(),
	}
}

func calendarSyncSyncErrorToPb(u *usecase.SyncError) *calendarsyncv1.SyncError {
	if u == nil {
		return nil
	}
	return &calendarsyncv1.SyncError{
		CalendarId: u.CalendarID,
		Error:      u.Error,
	}
}

func calendarSyncPbToLastRun(p *calendarsyncv1.LastRun) *usecase.LastRun {
	if p == nil {
		return nil
	}
	return &usecase.LastRun{
		SourceEvents: p.GetSourceEvents(),
		Mirrors:      p.GetMirrors(),
		Writes:       p.GetWrites(),
		Deletes:      p.GetDeletes(),
		Pending:      p.GetPending(),
		Errors: func(l []*calendarsyncv1.SyncError) []*usecase.SyncError {
			if l == nil {
				return nil
			}
			out := make([]*usecase.SyncError, 0, len(l))
			for _, v := range l {
				out = append(out, calendarSyncPbToSyncError(v))
			}
			return out
		}(p.GetErrors()),
		At:         p.GetAt(),
		DurationMs: p.GetDurationMs(),
		Reconnect:  p.GetReconnect(),
	}
}

func calendarSyncLastRunToPb(u *usecase.LastRun) *calendarsyncv1.LastRun {
	if u == nil {
		return nil
	}
	return &calendarsyncv1.LastRun{
		SourceEvents: u.SourceEvents,
		Mirrors:      u.Mirrors,
		Writes:       u.Writes,
		Deletes:      u.Deletes,
		Pending:      u.Pending,
		Errors: func(l []*usecase.SyncError) []*calendarsyncv1.SyncError {
			if l == nil {
				return nil
			}
			out := make([]*calendarsyncv1.SyncError, 0, len(l))
			for _, v := range l {
				out = append(out, calendarSyncSyncErrorToPb(v))
			}
			return out
		}(u.Errors),
		At:         u.At,
		DurationMs: u.DurationMs,
		Reconnect:  u.Reconnect,
	}
}
