// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type {{.Name}} struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} `gorm:"{{gormTag .}}"`
{{- end}}
}

func ({{.Name}}) TableName() string { return "{{.Plural}}" }

func New{{.Name}}(
{{- range .Fields}}
	{{.ParamName}} {{.GoType}},
{{- end}}
) (*{{.Name}}, error) {
{{- range .Fields}}
{{- if .IsPK}}
	if {{.ParamName}} == "" {
		return nil, errors.New("{{.SnakeName}} is required")
	}
{{- end}}
{{- if and .IsRequired (eq .GoType "string")}}
	{{.ParamName}} = strings.TrimSpace({{.ParamName}})
	if {{.ParamName}} == "" {
		return nil, errors.New("{{.SnakeName}} is required")
	}
{{- end}}
{{- if .IsEmail}}
	{{.ParamName}} = strings.TrimSpace({{.ParamName}})
	if {{.ParamName}} == "" || !strings.Contains({{.ParamName}}, "@") {
		return nil, errors.New("{{.SnakeName}} is invalid")
	}
{{- end}}
{{- end}}
	return &{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: {{.ParamName}},
{{- end}}
	}, nil
}

var _ = time.Time{}

// @required / @email の文字列フィールドが無いエンティティでも import が使われるようにする
var _ = strings.TrimSpace
