---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: content-env
  namespace: taramanji-dev
spec:
  encryptedData:
    REDIS_URL: AgB/suguFm8n3lusRGcuC0uRw3fHGPtj5CGiG3hYRTUbzxDOl+E4NkGHTuRgAq2Q2xxMg+bcCV1CwwW8NNWISIZ8FfW8V7gMkS64i8OR984bF/YD5YLXvOm2w1c/R4abwno40MrYm+CmgLZTlADKhUOrzSkU2fuPr7PKCVDiZmge3U00IbF/3sBzdAS3pcEUKL5xA11peDFcspmvUuNwL/Ykn2rR5XLi3Z+8VyxcjI4bcznCMo8XAW0s7tLEmOs3DjhC8XIKDjJqG9fPLJa6FV2sI6kEG/TVsE2zlGLtD0H2c9Dux8Tcewxws+OInDHbbhq6pp4Zv4pVEvqj6c/Kfq/DGO643RDGhOlWdkDYbtJbMzqKXhlfbO/8YHakcOU10C6vGNsZ25/Ge966cduBDva22z+Vru0EPl5lsqQgS126vF58aV0B4Fg/+1iDfTqAWeuRGc5HF24y4LwNCSqD9pDJjfhX4xQzQdnCJ1VyZkl8RZIC0t7TGQ11/ljdXIVjuV2pkQalXKRvSoyMdZbqBktgFObyrBp0e81OapEi7XOcSAFjvjIF+FUcRFc1W8EeMN0VIjwWlsVkiCCvf4PURk2W9/G3UktZ6nMddpxei+wR+cAvOmFYCX+iUXE2ejztln7HaWKJ40lXUzJT7k6CYOkmL1TZw/YdUaReE1L7C/myCHFAW42dS1u46oHWY32Y9breRCFaZzzf/zUXHNxWKPNc13G6LGLIBho863PzmXBeJr3TqBusQglmgyzAQJ8fD6cDf7XMXMjfA3MpRVJiXm0eV4R/YUDOn1KYuY+U8LZ2zZ1vZ8R4Q1YX0j6pBR9G3XyRYPSjL/UXghDzYdJbvOgZ
  template:
    metadata:
      name: content-env
      namespace: taramanji-dev
