---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: content-env
  namespace: taramanji
spec:
  encryptedData:
    REDIS_URL: AgBbaykZCLWITLcN8Ln26wFDfku2ybwyNzdlFfRYb1gXEB/+Jq03GsyQ2bxhO0dxYLOjl/4uvxhaClZdMtOkioxswkE4DreTKz/AqEi5+IXkUEEx8FRXNX4WritefRYvdChvAIKorqPUEbs7d83EWKUrOEeI46D54mStV86vGs/zaFxtO88/Vc4TWI8FAPMLAb5F3mS5RW/L+JnxrM5pFkYWQiZii/nV75oD3foORNCSqhA6RCE+LkEu1ItrgpeFxjNge6Vr6BZCAo8ttLDCzCZzNTsZi/gHxES7OfrXNHxmIAo8ahV/ZMybmB0iKs+8yPyZcqLa2lYbd5xmGyIb8Ef1G4A/zk0pIMBIzhbff3z15NShIiFwfLPoFF3DJhqZkHfaiORv4ljG9mjDtlDd3G3Vlj3Ql0YyxvdU1ip4W8PdHMxQilKxLlpfFx/9PfofhKRgHb4NcKzgm8GPrbylKGp6pyN7iYdvorfngowLYf0eiiVkrWuwq5q2A2df/BDMqoEzmbli9ZWqBgJKviTLgpGdtNMJy7Ftes73I+qgJxPRcwnkgjtBFfUGsZlkarGhnq8N8DwVjqmibMnjxLYRKYpv8BZGZnSn5MiMwr7GZYwncOW6pgo3HpPlhlgdesJ5SakGXt8Tl7A7zBsc2InBzqo6CDy5ue74FY7Juxq5QCUy6mjKRVj6jjXTlQwFctXSusEnSFTL5m89ZsZBxIz40N9LiO9IHjr0yV2NPwoGwHBVYtP0RW07Aa/sF9iwf2FjaoXfrCofchbmMn8b//N8kD8tNEWVUP6y1f2A5wwvloiOuzl0T+Uom+B2GaQ6nMDJmHiGHqhPz5ww
  template:
    metadata:
      name: content-env
      namespace: taramanji
