---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: content-env
  namespace: taramanji
spec:
  encryptedData:
    REDIS_URL: AgACsZM8r5TC2g4olrAe8apW1znx1kM7bOh7p9Iq3ZqrexLggDam5DIF2/0i63/H5p7o2U+2SQR5Xqytr3/L6XG+WEeRxTiselDyzmNuGSgUnKST+qnmvSyV1Y4BEFvC9UY2ysh9p5iCjjvKwVA3A58dI+u3OskIYyjNjO7xaoHQ6Wg9Ut23vjMq6uQcEKfTjFOU1M9k7pe2oSwRVXNmVhKthlpuxKUHZDETCmt/HdzWQLddA+gETtlT8hfYdD0mNjho05PFjcFUzg9rKWE1uQajFFryN8QA4Qo9IJjxs5ju5JgWEJgTDu11mX8wGJOHEDKsMMuSLX05MKAof4OWE4CkOsnX+ucxquEQYA5SyHXf9wi9eKhUpZ4WfqRunNToX9BFeD+hUiSLGiwC+QDRzuwb2lfq3STOeK+u7TXDN5pYEmvgYIl/RiQwfpM6ow7Go2c5FmQ0DF0kINGkXq+vIIqP5KQPeogbMv9pg+MiQSRUedfEvBQDIKQTJ0TZCn40wctIsaK8YkuZlkivYGWLJOJmcmdDnzt7gDgRlB3GB7a1kckPSTZ8dvoygcja3SzwdQ9BJ+zL2Idzohfj85Rz73oxhOGLrfxlNW9Cr5atWIPHcGmuaZgspJzGl9YX+tnKn/048PwFP2onwjdFGenlsXSS/YxRru7b6issmmKdgJfjYglYczlcS4X4/K9F59P9/BL0MQImYE4s6RkEPdUeg12a2suLIjzDUPoi1NT/F/O3fRkuYPzSicomvaXV4FQTbCM+co8Sa+1PA6JDcwC/N8t/m5yb9o3fOP+JSUNtU/FLhvgiub5xYuzuHqES0Q9O5FXnooN7XCxa
  template:
    metadata:
      name: content-env
      namespace: taramanji
