// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/calendarsync/v1/calendarsyncv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	CalendarSyncService *handler.CalendarSyncHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	calendarSyncUsecase usecase.CalendarSyncUsecase,
) *Handlers {
	return &Handlers{
		CalendarSyncService: handler.NewCalendarSyncHandler(calendarSyncUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(calendarsyncv1connect.NewCalendarSyncServiceHandler(h.CalendarSyncService, opts...))
}
