// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	reservationv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/reservation/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/reservation/v1/reservationv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/reservation/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// ReservationHandler は ReservationService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type ReservationHandler struct {
	usecase usecase.ReservationUsecase
}

func NewReservationHandler(uc usecase.ReservationUsecase) *ReservationHandler {
	return &ReservationHandler{usecase: uc}
}

var _ reservationv1connect.ReservationServiceHandler = (*ReservationHandler)(nil)

func (h *ReservationHandler) CreateReservation(ctx context.Context, req *connect.Request[reservationv1.CreateReservationRequest]) (*connect.Response[reservationv1.CreateReservationResponse], error) {
	out, err := h.usecase.CreateReservation(ctx, usecase.CreateReservationInput{
		Year:               req.Msg.GetYear(),
		Month:              req.Msg.GetMonth(),
		Day:                req.Msg.GetDay(),
		Weekday:            req.Msg.GetWeekday(),
		Start:              reservationPbToClockTime(req.Msg.GetStart()),
		End:                reservationPbToClockTime(req.Msg.GetEnd()),
		Name:               req.Msg.GetName(),
		Email:              req.Msg.GetEmail(),
		Purpose:            req.Msg.GetPurpose(),
		ContactMethod:      req.Msg.GetContactMethod(),
		DiscordName:        req.Msg.GetDiscordName(),
		DiscordServer:      req.Msg.GetDiscordServer(),
		SlackName:          req.Msg.GetSlackName(),
		SlackWorkspace:     req.Msg.GetSlackWorkspace(),
		OtherNote:          req.Msg.GetOtherNote(),
		OfflinePlaceLink:   req.Msg.GetOfflinePlaceLink(),
		OfflinePlaceName:   req.Msg.GetOfflinePlaceName(),
		OfflinePlaceDetail: req.Msg.GetOfflinePlaceDetail(),
		MeetingNote:        req.Msg.GetMeetingNote(),
		Location:           req.Msg.GetLocation(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.CreateReservationResponse{EventId: out.EventID, HtmlLink: out.HtmlLink, MeetLink: out.MeetLink, Invited: out.Invited, Note: out.Note, Status: out.Status}), nil
}

func (h *ReservationHandler) GetReservation(ctx context.Context, req *connect.Request[reservationv1.GetReservationRequest]) (*connect.Response[reservationv1.GetReservationResponse], error) {
	out, err := h.usecase.GetReservation(ctx, usecase.GetReservationInput{
		EventID: req.Msg.GetEventId(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.GetReservationResponse{EventId: out.EventID, HtmlLink: out.HtmlLink, MeetLink: out.MeetLink}), nil
}

func (h *ReservationHandler) CancelReservation(ctx context.Context, req *connect.Request[reservationv1.CancelReservationRequest]) (*connect.Response[reservationv1.CancelReservationResponse], error) {
	out, err := h.usecase.CancelReservation(ctx, usecase.CancelReservationInput{
		EventID: req.Msg.GetEventId(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.CancelReservationResponse{Deleted: out.Deleted, Suggestion: out.Suggestion, Status: out.Status}), nil
}

func (h *ReservationHandler) GetBusy(ctx context.Context, req *connect.Request[reservationv1.GetBusyRequest]) (*connect.Response[reservationv1.GetBusyResponse], error) {
	out, err := h.usecase.GetBusy(ctx, usecase.GetBusyInput{
		WeekStartIso: req.Msg.GetWeekStartIso(),
		NoBuffer:     req.Msg.GetNoBuffer(),
		Debug:        req.Msg.GetDebug(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.GetBusyResponse{Busy: func(l []*usecase.Interval) []*reservationv1.Interval {
		if l == nil {
			return nil
		}
		out := make([]*reservationv1.Interval, 0, len(l))
		for _, v := range l {
			out = append(out, reservationIntervalToPb(v))
		}
		return out
	}(out.Busy), SourceCount: out.SourceCount, Sources: func(l []*usecase.IcalSourceStatus) []*reservationv1.IcalSourceStatus {
		if l == nil {
			return nil
		}
		out := make([]*reservationv1.IcalSourceStatus, 0, len(l))
		for _, v := range l {
			out = append(out, reservationIcalSourceStatusToPb(v))
		}
		return out
	}(out.Sources)}), nil
}

func (h *ReservationHandler) ResolveMapsUrl(ctx context.Context, req *connect.Request[reservationv1.ResolveMapsUrlRequest]) (*connect.Response[reservationv1.ResolveMapsUrlResponse], error) {
	out, err := h.usecase.ResolveMapsUrl(ctx, usecase.ResolveMapsUrlInput{
		URL: req.Msg.GetUrl(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.ResolveMapsUrlResponse{Name: out.Name, FinalUrl: out.FinalURL, Error: out.Error}), nil
}

func (h *ReservationHandler) ReserveResearch(ctx context.Context, req *connect.Request[reservationv1.ReserveResearchRequest]) (*connect.Response[reservationv1.ReserveResearchResponse], error) {
	if err := h.usecase.ReserveResearch(ctx, usecase.ReserveResearchInput{}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.ReserveResearchResponse{}), nil
}

func (h *ReservationHandler) ListIcalSources(ctx context.Context, req *connect.Request[reservationv1.ListIcalSourcesRequest]) (*connect.Response[reservationv1.ListIcalSourcesResponse], error) {
	out, err := h.usecase.ListIcalSources(ctx, usecase.ListIcalSourcesInput{
		WeekStartIso: req.Msg.GetWeekStartIso(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&reservationv1.ListIcalSourcesResponse{Sources: func(l []*usecase.IcalSourceStatus) []*reservationv1.IcalSourceStatus {
		if l == nil {
			return nil
		}
		out := make([]*reservationv1.IcalSourceStatus, 0, len(l))
		for _, v := range l {
			out = append(out, reservationIcalSourceStatusToPb(v))
		}
		return out
	}(out.Sources), Events: func(l []*usecase.IcalEvent) []*reservationv1.IcalEvent {
		if l == nil {
			return nil
		}
		out := make([]*reservationv1.IcalEvent, 0, len(l))
		for _, v := range l {
			out = append(out, reservationIcalEventToPb(v))
		}
		return out
	}(out.Events), WeekStart: out.WeekStart, WeekEnd: out.WeekEnd}), nil
}

func reservationPbToClockTime(p *reservationv1.ClockTime) *usecase.ClockTime {
	if p == nil {
		return nil
	}
	return &usecase.ClockTime{
		Hour:   p.GetHour(),
		Minute: p.GetMinute(),
	}
}

func reservationClockTimeToPb(u *usecase.ClockTime) *reservationv1.ClockTime {
	if u == nil {
		return nil
	}
	return &reservationv1.ClockTime{
		Hour:   u.Hour,
		Minute: u.Minute,
	}
}

func reservationPbToInterval(p *reservationv1.Interval) *usecase.Interval {
	if p == nil {
		return nil
	}
	return &usecase.Interval{
		Start: p.GetStart(),
		End:   p.GetEnd(),
	}
}

func reservationIntervalToPb(u *usecase.Interval) *reservationv1.Interval {
	if u == nil {
		return nil
	}
	return &reservationv1.Interval{
		Start: u.Start,
		End:   u.End,
	}
}

func reservationPbToIcalSourceStatus(p *reservationv1.IcalSourceStatus) *usecase.IcalSourceStatus {
	if p == nil {
		return nil
	}
	return &usecase.IcalSourceStatus{
		URL:        p.GetUrl(),
		Name:       p.GetName(),
		Ok:         p.GetOk(),
		Status:     p.GetStatus(),
		Length:     p.GetLength(),
		EventCount: p.GetEventCount(),
	}
}

func reservationIcalSourceStatusToPb(u *usecase.IcalSourceStatus) *reservationv1.IcalSourceStatus {
	if u == nil {
		return nil
	}
	return &reservationv1.IcalSourceStatus{
		Url:        u.URL,
		Name:       u.Name,
		Ok:         u.Ok,
		Status:     u.Status,
		Length:     u.Length,
		EventCount: u.EventCount,
	}
}

func reservationPbToIcalEvent(p *reservationv1.IcalEvent) *usecase.IcalEvent {
	if p == nil {
		return nil
	}
	return &usecase.IcalEvent{
		Start:     p.GetStart(),
		End:       p.GetEnd(),
		Summary:   p.GetSummary(),
		Source:    p.GetSource(),
		SourceURL: p.GetSourceUrl(),
	}
}

func reservationIcalEventToPb(u *usecase.IcalEvent) *reservationv1.IcalEvent {
	if u == nil {
		return nil
	}
	return &reservationv1.IcalEvent{
		Start:     u.Start,
		End:       u.End,
		Summary:   u.Summary,
		Source:    u.Source,
		SourceUrl: u.SourceURL,
	}
}
