apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calendar-sync
resources:
  - namespace.yaml
  - ../redis
  - app.yaml
  - cronjob.yaml
secretGenerator:
  - name: calendar-sync-secrets
    envs:
      - secret.env
images:
  - name: taramanji-web
    newTag: local
