---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: content-env
  namespace: taramanji-stg
spec:
  encryptedData:
    REDIS_URL: AgAX/I/D+bC0lq2wZyyobrVdBVLwx16RuV0hHbtQAfwgSGXxPEqVGbrt8LTmmI/5o4T3RFn03uVhzriMxamuTkBA+zlN5f9ormfHyzD2RDVKYRI8jZvrqQ9RhOoFtTdJyeSLvNe8oTtkZheLFXhozCP1nZ1OwUcHfJS1D1d0ZdJ2Inc+y7nsxWXi8dFmKO51STDSHeoDCYGKd8nd2D4Pvkd/fStmsTQNuNA5H2dRXOGet9nO8J/L8QE2dWldvxxsSvef2D2LLborntiNzkTBUtFtEC4sv0pRvBq+e/dJLEGcrB0t8zOl/N1wzi1FE2bgOdytILrK+/Di/jLmwzum7XoWRQtkxqylsu8JiYZS0kwdanMGUHZEqA6JXgZyPFURd8ma+KAvxgJ2z7qDUcsniBAup7Muos9Xwl0InJMnNyVmUcedLAl+k7eLabL9jzNJgVAPDkpTT5aYTeG9QiaAD7mbKf65DHNGlaqC/6jM8i7zrTVp7NwVblpJnQciHmZ6QdmLkKZDUdnluPiD56FniQed2xpwvtbBtIKaCLx9iY3SxZ7YEZSD8dBccCbY09rtTPCq+LgkXeItGDxgnFh6FD+iFzPcSlQc82Nft47oDCXTi33FzOZkOsejP1I7T450Tk7puVe0NoQnRpMVbocYqArwV5VRiRJqro9Q3RzTVh7nWGHOl0qrPODi7qSvudyFGhmX91yzP9X326xP2CL++OPUsrcQoc+ck1pMHkxZ9jWjyqwEShdQZzz+ijS7oQy+GGA2C1EnW4jadhEpeQjAxKgyuQBN7heSYkfs56bX70zKc1vkvQnLGzGUjTrYCH+XFsfjOR88ktYnoblV7LVELkV4
  template:
    metadata:
      name: content-env
      namespace: taramanji-stg
