// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/identity/v1/identityv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/identity/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/identity/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	IdentityService *handler.IdentityHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	identityUsecase usecase.IdentityUsecase,
) *Handlers {
	return &Handlers{
		IdentityService: handler.NewIdentityHandler(identityUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(identityv1connect.NewIdentityServiceHandler(h.IdentityService, opts...))
}
