// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	notificationv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/notification/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/notification/v1/notificationv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/notification/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// NotificationHandler は NotificationService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type NotificationHandler struct {
	usecase usecase.NotificationUsecase
}

func NewNotificationHandler(uc usecase.NotificationUsecase) *NotificationHandler {
	return &NotificationHandler{usecase: uc}
}

var _ notificationv1connect.NotificationServiceHandler = (*NotificationHandler)(nil)

func (h *NotificationHandler) SendEmail(ctx context.Context, req *connect.Request[notificationv1.SendEmailRequest]) (*connect.Response[notificationv1.SendEmailResponse], error) {
	out, err := h.usecase.SendEmail(ctx, usecase.SendEmailInput{
		To:      req.Msg.GetTo(),
		Subject: req.Msg.GetSubject(),
		Text:    req.Msg.GetText(),
		Attachments: func(l []*notificationv1.Attachment) []*usecase.Attachment {
			if l == nil {
				return nil
			}
			out := make([]*usecase.Attachment, 0, len(l))
			for _, v := range l {
				out = append(out, notificationPbToAttachment(v))
			}
			return out
		}(req.Msg.GetAttachments()),
		RequireDelivery: req.Msg.GetRequireDelivery(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&notificationv1.SendEmailResponse{MessageId: out.MessageID, Dev: out.Dev}), nil
}

func notificationPbToAttachment(p *notificationv1.Attachment) *usecase.Attachment {
	if p == nil {
		return nil
	}
	return &usecase.Attachment{
		Filename:    p.GetFilename(),
		ContentType: p.GetContentType(),
		Data:        p.GetData(),
	}
}

func notificationAttachmentToPb(u *usecase.Attachment) *notificationv1.Attachment {
	if u == nil {
		return nil
	}
	return &notificationv1.Attachment{
		Filename:    u.Filename,
		ContentType: u.ContentType,
		Data:        u.Data,
	}
}
