// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type SendEmailInput struct {
	To              []string
	Subject         string
	Text            string
	Attachments     []*Attachment
	RequireDelivery bool
}

type SendEmailOutput struct {
	MessageID string `json:"message_id"`
	Dev       bool   `json:"dev"`
}

type Attachment struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Data        []byte `json:"data"`
}

// NotificationUsecase は NotificationService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type NotificationUsecase interface {
	SendEmail(ctx context.Context, input SendEmailInput) (*SendEmailOutput, error)
}
