// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/reservation/v1/reservationv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/reservation/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/reservation/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	ReservationService *handler.ReservationHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	reservationUsecase usecase.ReservationUsecase,
) *Handlers {
	return &Handlers{
		ReservationService: handler.NewReservationHandler(reservationUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(reservationv1connect.NewReservationServiceHandler(h.ReservationService, opts...))
}
