// app/layout.tsx
"use client";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";
import { BackgroundFetcher } from "../components/BackgroundFetcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head>
        <title>taramanji (JavaLangRuntimeException) ポートフォリオリンク集</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${inter.className} min-h-screen w-full`}>
        <Provider>
          <BackgroundFetcher />
          {children}
        </Provider>
      </body>
    </html>
  );
}
