// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type SubmitContactInput struct {
	Email        string
	Name         string
	Organization string
	Subject      string
	Purpose      string
	Message      string
	EventID      string
	Files        []*ContactFile
}

type SubmitQuestionnaireInput struct {
	Name         string
	VrUsage      string
	Height       float64
	TrialPattern string
	Responses    map[string]int32
}

type SendAdminEmailInput struct {
	To      string
	Subject string
	Body    string
}

type SendAdminEmailOutput struct {
	MessageID string `json:"message_id"`
	Dev       bool   `json:"dev"`
}

type ContactFile struct {
	Name        string `json:"name"`
	ContentType string `json:"content_type"`
	Data        []byte `json:"data"`
}

// InquiryUsecase は InquiryService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type InquiryUsecase interface {
	SubmitContact(ctx context.Context, input SubmitContactInput) error
	SubmitQuestionnaire(ctx context.Context, input SubmitQuestionnaireInput) error
	SendAdminEmail(ctx context.Context, input SendAdminEmailInput) (*SendAdminEmailOutput, error)
}
