// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type ListWorkLocationsInput struct{}

type SetWorkLocationsInput struct {
	Dates    []string
	Location string
}

type DeleteWorkLocationInput struct {
	Date string
}

type GetWorkLocationInput struct {
	Date string
}

type ListWorkLocationsOutput struct {
	Locations map[string]string `json:"locations"`
}

type SetWorkLocationsOutput struct {
	Count int32 `json:"count"`
}

type GetWorkLocationOutput struct {
	Location string `json:"location"`
}

// WorkLocationUsecase は WorkLocationService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type WorkLocationUsecase interface {
	ListWorkLocations(ctx context.Context, input ListWorkLocationsInput) (*ListWorkLocationsOutput, error)
	SetWorkLocations(ctx context.Context, input SetWorkLocationsInput) (*SetWorkLocationsOutput, error)
	DeleteWorkLocation(ctx context.Context, input DeleteWorkLocationInput) error
	GetWorkLocation(ctx context.Context, input GetWorkLocationInput) (*GetWorkLocationOutput, error)
}
