// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/content/v1/contentv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/content/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/content/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	ContentService *handler.ContentHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	contentUsecase usecase.ContentUsecase,
) *Handlers {
	return &Handlers{
		ContentService: handler.NewContentHandler(contentUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(contentv1connect.NewContentServiceHandler(h.ContentService, opts...))
}
