// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	inquiryv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/inquiry/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/inquiry/v1/inquiryv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/inquiry/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// InquiryHandler は InquiryService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type InquiryHandler struct {
	usecase usecase.InquiryUsecase
}

func NewInquiryHandler(uc usecase.InquiryUsecase) *InquiryHandler {
	return &InquiryHandler{usecase: uc}
}

var _ inquiryv1connect.InquiryServiceHandler = (*InquiryHandler)(nil)

func (h *InquiryHandler) SubmitContact(ctx context.Context, req *connect.Request[inquiryv1.SubmitContactRequest]) (*connect.Response[inquiryv1.SubmitContactResponse], error) {
	if err := h.usecase.SubmitContact(ctx, usecase.SubmitContactInput{
		Email:        req.Msg.GetEmail(),
		Name:         req.Msg.GetName(),
		Organization: req.Msg.GetOrganization(),
		Subject:      req.Msg.GetSubject(),
		Purpose:      req.Msg.GetPurpose(),
		Message:      req.Msg.GetMessage(),
		EventID:      req.Msg.GetEventId(),
		Files: func(l []*inquiryv1.ContactFile) []*usecase.ContactFile {
			if l == nil {
				return nil
			}
			out := make([]*usecase.ContactFile, 0, len(l))
			for _, v := range l {
				out = append(out, inquiryPbToContactFile(v))
			}
			return out
		}(req.Msg.GetFiles()),
	}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&inquiryv1.SubmitContactResponse{}), nil
}

func (h *InquiryHandler) SubmitQuestionnaire(ctx context.Context, req *connect.Request[inquiryv1.SubmitQuestionnaireRequest]) (*connect.Response[inquiryv1.SubmitQuestionnaireResponse], error) {
	if err := h.usecase.SubmitQuestionnaire(ctx, usecase.SubmitQuestionnaireInput{
		Name:         req.Msg.GetName(),
		VrUsage:      req.Msg.GetVrUsage(),
		Height:       req.Msg.GetHeight(),
		TrialPattern: req.Msg.GetTrialPattern(),
		Responses:    req.Msg.GetResponses(),
	}); err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&inquiryv1.SubmitQuestionnaireResponse{}), nil
}

func (h *InquiryHandler) SendAdminEmail(ctx context.Context, req *connect.Request[inquiryv1.SendAdminEmailRequest]) (*connect.Response[inquiryv1.SendAdminEmailResponse], error) {
	out, err := h.usecase.SendAdminEmail(ctx, usecase.SendAdminEmailInput{
		To:      req.Msg.GetTo(),
		Subject: req.Msg.GetSubject(),
		Body:    req.Msg.GetBody(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&inquiryv1.SendAdminEmailResponse{MessageId: out.MessageID, Dev: out.Dev}), nil
}

func inquiryPbToContactFile(p *inquiryv1.ContactFile) *usecase.ContactFile {
	if p == nil {
		return nil
	}
	return &usecase.ContactFile{
		Name:        p.GetName(),
		ContentType: p.GetContentType(),
		Data:        p.GetData(),
	}
}

func inquiryContactFileToPb(u *usecase.ContactFile) *inquiryv1.ContactFile {
	if u == nil {
		return nil
	}
	return &inquiryv1.ContactFile{
		Name:        u.Name,
		ContentType: u.ContentType,
		Data:        u.Data,
	}
}
