// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"
{{range .Services}}
	"{{.Connect.ConnectImport}}"
{{- end}}

	"{{.ImportHandler}}"
	"{{.ImportUsecase}}"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
{{- range .Services}}
	{{.ServiceName}} *handler.{{.HandlerTypeName}}
{{- end}}
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
{{- range .Services}}
	{{.UsecaseParamName}} usecase.{{.UsecaseTypeName}},
{{- end}}
) *Handlers {
	return &Handlers{
{{- range .Services}}
		{{.ServiceName}}: handler.New{{.HandlerTypeName}}({{.UsecaseParamName}}),
{{- end}}
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
{{- range .Services}}
	mux.Handle({{.Connect.ConnectPkg}}.New{{.Connect.ServiceGoName}}Handler(h.{{.ServiceName}}, opts...))
{{- end}}
}
