// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// Redis への保存形式（docs/patterns/infra-swap.md: string に JSON エンコード）。
// 本体は calendarAccounts:rec:<pk>、@unique の副次インデックスは calendarAccounts:idx:<field>:<value> → pk。
type redisCalendarAccountRecord struct {
	CalendarID   string    `json:"calendar_id"`
	RefreshToken string    `json:"refresh_token"`
	Private      bool      `json:"private"`
	ConnectedAt  time.Time `json:"connected_at"`
	ColorID      string    `json:"color_id"`
}

func toCalendarAccountRecord(e *entity.CalendarAccount) redisCalendarAccountRecord {
	return redisCalendarAccountRecord{
		CalendarID:   e.CalendarID,
		RefreshToken: e.RefreshToken,
		Private:      e.Private,
		ConnectedAt:  e.ConnectedAt,
		ColorID:      e.ColorID,
	}
}

func (r redisCalendarAccountRecord) toEntity() *entity.CalendarAccount {
	return &entity.CalendarAccount{
		CalendarID:   r.CalendarID,
		RefreshToken: r.RefreshToken,
		Private:      r.Private,
		ConnectedAt:  r.ConnectedAt,
		ColorID:      r.ColorID,
	}
}

type redisCalendarAccountRepository struct {
	client redis.UniversalClient
}

func NewRedisCalendarAccountRepository(client redis.UniversalClient) repository.CalendarAccountRepository {
	return &redisCalendarAccountRepository{client: client}
}

var _ repository.CalendarAccountRepository = (*redisCalendarAccountRepository)(nil)
var _ = time.Time{}

const calendarAccountKeyPrefix = "calendarAccounts:rec:"

func calendarAccountKey(pk string) string { return calendarAccountKeyPrefix + fmt.Sprint(pk) }

func calendarAccountIndexKeys(e *entity.CalendarAccount) []string {
	return []string{}
}

func (r *redisCalendarAccountRepository) get(ctx context.Context, key string) (*entity.CalendarAccount, error) {
	raw, err := r.client.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rec redisCalendarAccountRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("decode %s: %w", key, err)
	}
	return rec.toEntity(), nil
}

func (r *redisCalendarAccountRepository) SelectAll(ctx context.Context) ([]*entity.CalendarAccount, error) {
	var keys []string
	iter := r.client.Scan(ctx, 0, calendarAccountKeyPrefix+"*", 500).Iterator()
	for iter.Next(ctx) {
		keys = append(keys, iter.Val())
	}
	if err := iter.Err(); err != nil {
		return nil, err
	}
	out := make([]*entity.CalendarAccount, 0, len(keys))
	for start := 0; start < len(keys); start += 500 {
		end := min(start+500, len(keys))
		vals, err := r.client.MGet(ctx, keys[start:end]...).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			s, ok := v.(string)
			if !ok {
				continue // SCAN と MGET の間に消えた
			}
			var rec redisCalendarAccountRecord
			if err := json.Unmarshal([]byte(s), &rec); err != nil {
				return nil, fmt.Errorf("decode %s: %w", keys[start+i], err)
			}
			out = append(out, rec.toEntity())
		}
	}
	return out, nil
}

func (r *redisCalendarAccountRepository) SelectByPK(ctx context.Context, calendarId string) (*entity.CalendarAccount, error) {
	return r.get(ctx, calendarAccountKey(calendarId))
}

func (r *redisCalendarAccountRepository) Insert(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	raw, err := json.Marshal(toCalendarAccountRecord(calendarAccount))
	if err != nil {
		return err
	}
	key := calendarAccountKey(calendarAccount.CalendarID)
	ok, err := r.client.SetNX(ctx, key, raw, 0).Result()
	if err != nil {
		return err
	}
	if !ok {
		return repository.ErrCalendarAccountAlreadyExists
	}
	pk := fmt.Sprint(calendarAccount.CalendarID)
	var claimed []string
	for _, idx := range calendarAccountIndexKeys(calendarAccount) {
		ok, err := r.client.SetNX(ctx, idx, pk, 0).Result()
		if err != nil || !ok {
			// 一意制約違反: 先に書いた分を戻す
			r.client.Del(ctx, append(claimed, key)...)
			if err != nil {
				return err
			}
			return repository.ErrCalendarAccountAlreadyExists
		}
		claimed = append(claimed, idx)
	}
	return nil
}

func (r *redisCalendarAccountRepository) BulkInsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error {
	for _, e := range calendarAccounts {
		if err := r.Insert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisCalendarAccountRepository) Upsert(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	prev, err := r.SelectByPK(ctx, calendarAccount.CalendarID)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(toCalendarAccountRecord(calendarAccount))
	if err != nil {
		return err
	}
	pk := fmt.Sprint(calendarAccount.CalendarID)
	pipe := r.client.TxPipeline()
	if prev != nil {
		for _, idx := range calendarAccountIndexKeys(prev) {
			pipe.Del(ctx, idx)
		}
	}
	pipe.Set(ctx, calendarAccountKey(calendarAccount.CalendarID), raw, 0)
	for _, idx := range calendarAccountIndexKeys(calendarAccount) {
		pipe.Set(ctx, idx, pk, 0)
	}
	_, err = pipe.Exec(ctx)
	return err
}

func (r *redisCalendarAccountRepository) BulkUpsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error {
	for _, e := range calendarAccounts {
		if err := r.Upsert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisCalendarAccountRepository) Update(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	n, err := r.client.Exists(ctx, calendarAccountKey(calendarAccount.CalendarID)).Result()
	if err != nil {
		return err
	}
	if n == 0 {
		return repository.ErrCalendarAccountNotFound
	}
	return r.Upsert(ctx, calendarAccount)
}

func (r *redisCalendarAccountRepository) Delete(ctx context.Context, calendarId string) error {
	prev, err := r.SelectByPK(ctx, calendarId)
	if err != nil {
		return err
	}
	if prev == nil {
		return repository.ErrCalendarAccountNotFound
	}
	return r.client.Del(ctx, append(calendarAccountIndexKeys(prev), calendarAccountKey(calendarId))...).Err()
}

func (r *redisCalendarAccountRepository) BulkDelete(ctx context.Context, calendarIds []string) error {
	missing := false
	for _, pk := range calendarIds {
		if err := r.Delete(ctx, pk); err != nil {
			if errors.Is(err, repository.ErrCalendarAccountNotFound) {
				missing = true
				continue
			}
			return err
		}
	}
	if missing {
		return repository.ErrCalendarAccountNotFound
	}
	return nil
}

func (r *redisCalendarAccountRepository) DeleteAll(ctx context.Context) error {
	for _, pattern := range []string{calendarAccountKeyPrefix + "*", "calendarAccounts:idx:*"} {
		iter := r.client.Scan(ctx, 0, pattern, 500).Iterator()
		var keys []string
		for iter.Next(ctx) {
			keys = append(keys, iter.Val())
		}
		if err := iter.Err(); err != nil {
			return err
		}
		if len(keys) > 0 {
			if err := r.client.Del(ctx, keys...).Err(); err != nil {
				return err
			}
		}
	}
	return nil
}

var _ = sort.Strings
