// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// Redis への保存形式（docs/patterns/infra-swap.md: string に JSON エンコード）。
// 本体は syncSettings:rec:<pk>、@unique の副次インデックスは syncSettings:idx:<field>:<value> → pk。
type redisSyncSettingRecord struct {
	ID     string `json:"id"`
	Master string `json:"master"`
}

func toSyncSettingRecord(e *entity.SyncSetting) redisSyncSettingRecord {
	return redisSyncSettingRecord{
		ID:     e.ID,
		Master: e.Master,
	}
}

func (r redisSyncSettingRecord) toEntity() *entity.SyncSetting {
	return &entity.SyncSetting{
		ID:     r.ID,
		Master: r.Master,
	}
}

type redisSyncSettingRepository struct {
	client redis.UniversalClient
}

func NewRedisSyncSettingRepository(client redis.UniversalClient) repository.SyncSettingRepository {
	return &redisSyncSettingRepository{client: client}
}

var _ repository.SyncSettingRepository = (*redisSyncSettingRepository)(nil)
var _ = time.Time{}

const syncSettingKeyPrefix = "syncSettings:rec:"

func syncSettingKey(pk string) string { return syncSettingKeyPrefix + fmt.Sprint(pk) }

func syncSettingIndexKeys(e *entity.SyncSetting) []string {
	return []string{}
}

func (r *redisSyncSettingRepository) get(ctx context.Context, key string) (*entity.SyncSetting, error) {
	raw, err := r.client.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rec redisSyncSettingRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("decode %s: %w", key, err)
	}
	return rec.toEntity(), nil
}

func (r *redisSyncSettingRepository) SelectAll(ctx context.Context) ([]*entity.SyncSetting, error) {
	var keys []string
	iter := r.client.Scan(ctx, 0, syncSettingKeyPrefix+"*", 500).Iterator()
	for iter.Next(ctx) {
		keys = append(keys, iter.Val())
	}
	if err := iter.Err(); err != nil {
		return nil, err
	}
	out := make([]*entity.SyncSetting, 0, len(keys))
	for start := 0; start < len(keys); start += 500 {
		end := min(start+500, len(keys))
		vals, err := r.client.MGet(ctx, keys[start:end]...).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			s, ok := v.(string)
			if !ok {
				continue // SCAN と MGET の間に消えた
			}
			var rec redisSyncSettingRecord
			if err := json.Unmarshal([]byte(s), &rec); err != nil {
				return nil, fmt.Errorf("decode %s: %w", keys[start+i], err)
			}
			out = append(out, rec.toEntity())
		}
	}
	return out, nil
}

func (r *redisSyncSettingRepository) SelectByPK(ctx context.Context, id string) (*entity.SyncSetting, error) {
	return r.get(ctx, syncSettingKey(id))
}

func (r *redisSyncSettingRepository) Insert(ctx context.Context, syncSetting *entity.SyncSetting) error {
	raw, err := json.Marshal(toSyncSettingRecord(syncSetting))
	if err != nil {
		return err
	}
	key := syncSettingKey(syncSetting.ID)
	ok, err := r.client.SetNX(ctx, key, raw, 0).Result()
	if err != nil {
		return err
	}
	if !ok {
		return repository.ErrSyncSettingAlreadyExists
	}
	pk := fmt.Sprint(syncSetting.ID)
	var claimed []string
	for _, idx := range syncSettingIndexKeys(syncSetting) {
		ok, err := r.client.SetNX(ctx, idx, pk, 0).Result()
		if err != nil || !ok {
			// 一意制約違反: 先に書いた分を戻す
			r.client.Del(ctx, append(claimed, key)...)
			if err != nil {
				return err
			}
			return repository.ErrSyncSettingAlreadyExists
		}
		claimed = append(claimed, idx)
	}
	return nil
}

func (r *redisSyncSettingRepository) BulkInsert(ctx context.Context, syncSettings []*entity.SyncSetting) error {
	for _, e := range syncSettings {
		if err := r.Insert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisSyncSettingRepository) Upsert(ctx context.Context, syncSetting *entity.SyncSetting) error {
	prev, err := r.SelectByPK(ctx, syncSetting.ID)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(toSyncSettingRecord(syncSetting))
	if err != nil {
		return err
	}
	pk := fmt.Sprint(syncSetting.ID)
	pipe := r.client.TxPipeline()
	if prev != nil {
		for _, idx := range syncSettingIndexKeys(prev) {
			pipe.Del(ctx, idx)
		}
	}
	pipe.Set(ctx, syncSettingKey(syncSetting.ID), raw, 0)
	for _, idx := range syncSettingIndexKeys(syncSetting) {
		pipe.Set(ctx, idx, pk, 0)
	}
	_, err = pipe.Exec(ctx)
	return err
}

func (r *redisSyncSettingRepository) BulkUpsert(ctx context.Context, syncSettings []*entity.SyncSetting) error {
	for _, e := range syncSettings {
		if err := r.Upsert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisSyncSettingRepository) Update(ctx context.Context, syncSetting *entity.SyncSetting) error {
	n, err := r.client.Exists(ctx, syncSettingKey(syncSetting.ID)).Result()
	if err != nil {
		return err
	}
	if n == 0 {
		return repository.ErrSyncSettingNotFound
	}
	return r.Upsert(ctx, syncSetting)
}

func (r *redisSyncSettingRepository) Delete(ctx context.Context, id string) error {
	prev, err := r.SelectByPK(ctx, id)
	if err != nil {
		return err
	}
	if prev == nil {
		return repository.ErrSyncSettingNotFound
	}
	return r.client.Del(ctx, append(syncSettingIndexKeys(prev), syncSettingKey(id))...).Err()
}

func (r *redisSyncSettingRepository) BulkDelete(ctx context.Context, ids []string) error {
	missing := false
	for _, pk := range ids {
		if err := r.Delete(ctx, pk); err != nil {
			if errors.Is(err, repository.ErrSyncSettingNotFound) {
				missing = true
				continue
			}
			return err
		}
	}
	if missing {
		return repository.ErrSyncSettingNotFound
	}
	return nil
}

func (r *redisSyncSettingRepository) DeleteAll(ctx context.Context) error {
	for _, pattern := range []string{syncSettingKeyPrefix + "*", "syncSettings:idx:*"} {
		iter := r.client.Scan(ctx, 0, pattern, 500).Iterator()
		var keys []string
		for iter.Next(ctx) {
			keys = append(keys, iter.Val())
		}
		if err := iter.Err(); err != nil {
			return err
		}
		if len(keys) > 0 {
			if err := r.client.Del(ctx, keys...).Err(); err != nil {
				return err
			}
		}
	}
	return nil
}

var _ = sort.Strings
