// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// Redis への保存形式（docs/patterns/infra-swap.md: string に JSON エンコード）。
// 本体は syncMirrors:rec:<pk>、@unique の副次インデックスは syncMirrors:idx:<field>:<value> → pk。
type redisSyncMirrorRecord struct {
	Key    string `json:"key"`
	Digest string `json:"digest"`
	EndAt  string `json:"end_at"`
}

func toSyncMirrorRecord(e *entity.SyncMirror) redisSyncMirrorRecord {
	return redisSyncMirrorRecord{
		Key:    e.Key,
		Digest: e.Digest,
		EndAt:  e.EndAt,
	}
}

func (r redisSyncMirrorRecord) toEntity() *entity.SyncMirror {
	return &entity.SyncMirror{
		Key:    r.Key,
		Digest: r.Digest,
		EndAt:  r.EndAt,
	}
}

type redisSyncMirrorRepository struct {
	client redis.UniversalClient
}

func NewRedisSyncMirrorRepository(client redis.UniversalClient) repository.SyncMirrorRepository {
	return &redisSyncMirrorRepository{client: client}
}

var _ repository.SyncMirrorRepository = (*redisSyncMirrorRepository)(nil)
var _ = time.Time{}

const syncMirrorKeyPrefix = "syncMirrors:rec:"

func syncMirrorKey(pk string) string { return syncMirrorKeyPrefix + fmt.Sprint(pk) }

func syncMirrorIndexKeys(e *entity.SyncMirror) []string {
	return []string{}
}

func (r *redisSyncMirrorRepository) get(ctx context.Context, key string) (*entity.SyncMirror, error) {
	raw, err := r.client.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rec redisSyncMirrorRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("decode %s: %w", key, err)
	}
	return rec.toEntity(), nil
}

func (r *redisSyncMirrorRepository) SelectAll(ctx context.Context) ([]*entity.SyncMirror, error) {
	var keys []string
	iter := r.client.Scan(ctx, 0, syncMirrorKeyPrefix+"*", 500).Iterator()
	for iter.Next(ctx) {
		keys = append(keys, iter.Val())
	}
	if err := iter.Err(); err != nil {
		return nil, err
	}
	out := make([]*entity.SyncMirror, 0, len(keys))
	for start := 0; start < len(keys); start += 500 {
		end := min(start+500, len(keys))
		vals, err := r.client.MGet(ctx, keys[start:end]...).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			s, ok := v.(string)
			if !ok {
				continue // SCAN と MGET の間に消えた
			}
			var rec redisSyncMirrorRecord
			if err := json.Unmarshal([]byte(s), &rec); err != nil {
				return nil, fmt.Errorf("decode %s: %w", keys[start+i], err)
			}
			out = append(out, rec.toEntity())
		}
	}
	return out, nil
}

func (r *redisSyncMirrorRepository) SelectByPK(ctx context.Context, key string) (*entity.SyncMirror, error) {
	return r.get(ctx, syncMirrorKey(key))
}

func (r *redisSyncMirrorRepository) Insert(ctx context.Context, syncMirror *entity.SyncMirror) error {
	raw, err := json.Marshal(toSyncMirrorRecord(syncMirror))
	if err != nil {
		return err
	}
	key := syncMirrorKey(syncMirror.Key)
	ok, err := r.client.SetNX(ctx, key, raw, 0).Result()
	if err != nil {
		return err
	}
	if !ok {
		return repository.ErrSyncMirrorAlreadyExists
	}
	pk := fmt.Sprint(syncMirror.Key)
	var claimed []string
	for _, idx := range syncMirrorIndexKeys(syncMirror) {
		ok, err := r.client.SetNX(ctx, idx, pk, 0).Result()
		if err != nil || !ok {
			// 一意制約違反: 先に書いた分を戻す
			r.client.Del(ctx, append(claimed, key)...)
			if err != nil {
				return err
			}
			return repository.ErrSyncMirrorAlreadyExists
		}
		claimed = append(claimed, idx)
	}
	return nil
}

func (r *redisSyncMirrorRepository) BulkInsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error {
	for _, e := range syncMirrors {
		if err := r.Insert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisSyncMirrorRepository) Upsert(ctx context.Context, syncMirror *entity.SyncMirror) error {
	prev, err := r.SelectByPK(ctx, syncMirror.Key)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(toSyncMirrorRecord(syncMirror))
	if err != nil {
		return err
	}
	pk := fmt.Sprint(syncMirror.Key)
	pipe := r.client.TxPipeline()
	if prev != nil {
		for _, idx := range syncMirrorIndexKeys(prev) {
			pipe.Del(ctx, idx)
		}
	}
	pipe.Set(ctx, syncMirrorKey(syncMirror.Key), raw, 0)
	for _, idx := range syncMirrorIndexKeys(syncMirror) {
		pipe.Set(ctx, idx, pk, 0)
	}
	_, err = pipe.Exec(ctx)
	return err
}

func (r *redisSyncMirrorRepository) BulkUpsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error {
	for _, e := range syncMirrors {
		if err := r.Upsert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisSyncMirrorRepository) Update(ctx context.Context, syncMirror *entity.SyncMirror) error {
	n, err := r.client.Exists(ctx, syncMirrorKey(syncMirror.Key)).Result()
	if err != nil {
		return err
	}
	if n == 0 {
		return repository.ErrSyncMirrorNotFound
	}
	return r.Upsert(ctx, syncMirror)
}

func (r *redisSyncMirrorRepository) Delete(ctx context.Context, key string) error {
	prev, err := r.SelectByPK(ctx, key)
	if err != nil {
		return err
	}
	if prev == nil {
		return repository.ErrSyncMirrorNotFound
	}
	return r.client.Del(ctx, append(syncMirrorIndexKeys(prev), syncMirrorKey(key))...).Err()
}

func (r *redisSyncMirrorRepository) BulkDelete(ctx context.Context, keys []string) error {
	missing := false
	for _, pk := range keys {
		if err := r.Delete(ctx, pk); err != nil {
			if errors.Is(err, repository.ErrSyncMirrorNotFound) {
				missing = true
				continue
			}
			return err
		}
	}
	if missing {
		return repository.ErrSyncMirrorNotFound
	}
	return nil
}

func (r *redisSyncMirrorRepository) DeleteAll(ctx context.Context) error {
	for _, pattern := range []string{syncMirrorKeyPrefix + "*", "syncMirrors:idx:*"} {
		iter := r.client.Scan(ctx, 0, pattern, 500).Iterator()
		var keys []string
		for iter.Next(ctx) {
			keys = append(keys, iter.Val())
		}
		if err := iter.Err(); err != nil {
			return err
		}
		if len(keys) > 0 {
			if err := r.client.Del(ctx, keys...).Err(); err != nil {
				return err
			}
		}
	}
	return nil
}

var _ = sort.Strings
