// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/notification/v1/notificationv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/notification/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/notification/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	NotificationService *handler.NotificationHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	notificationUsecase usecase.NotificationUsecase,
) *Handlers {
	return &Handlers{
		NotificationService: handler.NewNotificationHandler(notificationUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(notificationv1connect.NewNotificationServiceHandler(h.NotificationService, opts...))
}
