// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	contentv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/content/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/content/v1/contentv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/content/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// ContentHandler は ContentService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type ContentHandler struct {
	usecase usecase.ContentUsecase
}

func NewContentHandler(uc usecase.ContentUsecase) *ContentHandler {
	return &ContentHandler{usecase: uc}
}

var _ contentv1connect.ContentServiceHandler = (*ContentHandler)(nil)

func (h *ContentHandler) ListQiitaItems(ctx context.Context, req *connect.Request[contentv1.ListQiitaItemsRequest]) (*connect.Response[contentv1.ListQiitaItemsResponse], error) {
	out, err := h.usecase.ListQiitaItems(ctx, usecase.ListQiitaItemsInput{
		Page:        req.Msg.GetPage(),
		Initial:     req.Msg.GetInitial(),
		IncludeTags: req.Msg.GetIncludeTags(),
		PerPage:     req.Msg.GetPerPage(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.ListQiitaItemsResponse{Urls: out.Urls, Items: func(l []*usecase.QiitaItem) []*contentv1.QiitaItem {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.QiitaItem, 0, len(l))
		for _, v := range l {
			out = append(out, contentQiitaItemToPb(v))
		}
		return out
	}(out.Items)}), nil
}

func (h *ContentHandler) ScrapeQiitaProfile(ctx context.Context, req *connect.Request[contentv1.ScrapeQiitaProfileRequest]) (*connect.Response[contentv1.ScrapeQiitaProfileResponse], error) {
	out, err := h.usecase.ScrapeQiitaProfile(ctx, usecase.ScrapeQiitaProfileInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.ScrapeQiitaProfileResponse{PickupArticles: func(l []*usecase.ScrapedArticle) []*contentv1.ScrapedArticle {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.ScrapedArticle, 0, len(l))
		for _, v := range l {
			out = append(out, contentScrapedArticleToPb(v))
		}
		return out
	}(out.PickupArticles), LatestArticles: func(l []*usecase.ScrapedArticle) []*contentv1.ScrapedArticle {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.ScrapedArticle, 0, len(l))
		for _, v := range l {
			out = append(out, contentScrapedArticleToPb(v))
		}
		return out
	}(out.LatestArticles)}), nil
}

func (h *ContentHandler) ScrapeQiitaArticleLinks(ctx context.Context, req *connect.Request[contentv1.ScrapeQiitaArticleLinksRequest]) (*connect.Response[contentv1.ScrapeQiitaArticleLinksResponse], error) {
	out, err := h.usecase.ScrapeQiitaArticleLinks(ctx, usecase.ScrapeQiitaArticleLinksInput{
		URL: req.Msg.GetUrl(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.ScrapeQiitaArticleLinksResponse{Links: func(l []*usecase.ArticleLink) []*contentv1.ArticleLink {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.ArticleLink, 0, len(l))
		for _, v := range l {
			out = append(out, contentArticleLinkToPb(v))
		}
		return out
	}(out.Links)}), nil
}

func (h *ContentHandler) ListConnpassEvents(ctx context.Context, req *connect.Request[contentv1.ListConnpassEventsRequest]) (*connect.Response[contentv1.ListConnpassEventsResponse], error) {
	out, err := h.usecase.ListConnpassEvents(ctx, usecase.ListConnpassEventsInput{
		Nickname: req.Msg.GetNickname(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.ListConnpassEventsResponse{ResultsReturned: out.ResultsReturned, ResultsAvailable: out.ResultsAvailable, ResultsStart: out.ResultsStart, Events: func(l []*usecase.ConnpassEvent) []*contentv1.ConnpassEvent {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.ConnpassEvent, 0, len(l))
		for _, v := range l {
			out = append(out, contentConnpassEventToPb(v))
		}
		return out
	}(out.Events)}), nil
}

func (h *ContentHandler) ListOrcidWorks(ctx context.Context, req *connect.Request[contentv1.ListOrcidWorksRequest]) (*connect.Response[contentv1.ListOrcidWorksResponse], error) {
	out, err := h.usecase.ListOrcidWorks(ctx, usecase.ListOrcidWorksInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.ListOrcidWorksResponse{OrcidId: out.OrcidID, Works: func(l []*usecase.OrcidWork) []*contentv1.OrcidWork {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.OrcidWork, 0, len(l))
		for _, v := range l {
			out = append(out, contentOrcidWorkToPb(v))
		}
		return out
	}(out.Works)}), nil
}

func (h *ContentHandler) GetOgp(ctx context.Context, req *connect.Request[contentv1.GetOgpRequest]) (*connect.Response[contentv1.GetOgpResponse], error) {
	out, err := h.usecase.GetOgp(ctx, usecase.GetOgpInput{
		Urls:    req.Msg.GetUrls(),
		NoCache: req.Msg.GetNoCache(),
	})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&contentv1.GetOgpResponse{Data: func(l []*usecase.Ogp) []*contentv1.Ogp {
		if l == nil {
			return nil
		}
		out := make([]*contentv1.Ogp, 0, len(l))
		for _, v := range l {
			out = append(out, contentOgpToPb(v))
		}
		return out
	}(out.Data)}), nil
}

func contentPbToQiitaTag(p *contentv1.QiitaTag) *usecase.QiitaTag {
	if p == nil {
		return nil
	}
	return &usecase.QiitaTag{
		Name:     p.GetName(),
		Versions: p.GetVersions(),
	}
}

func contentQiitaTagToPb(u *usecase.QiitaTag) *contentv1.QiitaTag {
	if u == nil {
		return nil
	}
	return &contentv1.QiitaTag{
		Name:     u.Name,
		Versions: u.Versions,
	}
}

func contentPbToQiitaItem(p *contentv1.QiitaItem) *usecase.QiitaItem {
	if p == nil {
		return nil
	}
	return &usecase.QiitaItem{
		URL:   p.GetUrl(),
		Title: p.GetTitle(),
		Body:  p.GetBody(),
		Tags: func(l []*contentv1.QiitaTag) []*usecase.QiitaTag {
			if l == nil {
				return nil
			}
			out := make([]*usecase.QiitaTag, 0, len(l))
			for _, v := range l {
				out = append(out, contentPbToQiitaTag(v))
			}
			return out
		}(p.GetTags()),
	}
}

func contentQiitaItemToPb(u *usecase.QiitaItem) *contentv1.QiitaItem {
	if u == nil {
		return nil
	}
	return &contentv1.QiitaItem{
		Url:   u.URL,
		Title: u.Title,
		Body:  u.Body,
		Tags: func(l []*usecase.QiitaTag) []*contentv1.QiitaTag {
			if l == nil {
				return nil
			}
			out := make([]*contentv1.QiitaTag, 0, len(l))
			for _, v := range l {
				out = append(out, contentQiitaTagToPb(v))
			}
			return out
		}(u.Tags),
	}
}

func contentPbToScrapedArticle(p *contentv1.ScrapedArticle) *usecase.ScrapedArticle {
	if p == nil {
		return nil
	}
	return &usecase.ScrapedArticle{
		URL:   p.GetUrl(),
		Title: p.GetTitle(),
		Tags:  p.GetTags(),
	}
}

func contentScrapedArticleToPb(u *usecase.ScrapedArticle) *contentv1.ScrapedArticle {
	if u == nil {
		return nil
	}
	return &contentv1.ScrapedArticle{
		Url:   u.URL,
		Title: u.Title,
		Tags:  u.Tags,
	}
}

func contentPbToArticleLink(p *contentv1.ArticleLink) *usecase.ArticleLink {
	if p == nil {
		return nil
	}
	return &usecase.ArticleLink{
		URL:   p.GetUrl(),
		Title: p.GetTitle(),
	}
}

func contentArticleLinkToPb(u *usecase.ArticleLink) *contentv1.ArticleLink {
	if u == nil {
		return nil
	}
	return &contentv1.ArticleLink{
		Url:   u.URL,
		Title: u.Title,
	}
}

func contentPbToConnpassEvent(p *contentv1.ConnpassEvent) *usecase.ConnpassEvent {
	if p == nil {
		return nil
	}
	return &usecase.ConnpassEvent{
		EventID:   p.GetEventId(),
		Title:     p.GetTitle(),
		Catch:     p.GetCatch(),
		EventURL:  p.GetEventUrl(),
		StartedAt: p.GetStartedAt(),
		EndedAt:   p.GetEndedAt(),
		Limit:     p.GetLimit(),
		Accepted:  p.GetAccepted(),
		Waiting:   p.GetWaiting(),
		Place:     p.GetPlace(),
		Address:   p.GetAddress(),
		ImageURL:  p.GetImageUrl(),
	}
}

func contentConnpassEventToPb(u *usecase.ConnpassEvent) *contentv1.ConnpassEvent {
	if u == nil {
		return nil
	}
	return &contentv1.ConnpassEvent{
		EventId:   u.EventID,
		Title:     u.Title,
		Catch:     u.Catch,
		EventUrl:  u.EventURL,
		StartedAt: u.StartedAt,
		EndedAt:   u.EndedAt,
		Limit:     u.Limit,
		Accepted:  u.Accepted,
		Waiting:   u.Waiting,
		Place:     u.Place,
		Address:   u.Address,
		ImageUrl:  u.ImageURL,
	}
}

func contentPbToOrcidWork(p *contentv1.OrcidWork) *usecase.OrcidWork {
	if p == nil {
		return nil
	}
	return &usecase.OrcidWork{
		PutCode: p.GetPutCode(),
		Title:   p.GetTitle(),
		Type:    p.GetType(),
		Venue:   p.GetVenue(),
		Date:    p.GetDate(),
		Doi:     p.GetDoi(),
		URL:     p.GetUrl(),
		Authors: p.GetAuthors(),
	}
}

func contentOrcidWorkToPb(u *usecase.OrcidWork) *contentv1.OrcidWork {
	if u == nil {
		return nil
	}
	return &contentv1.OrcidWork{
		PutCode: u.PutCode,
		Title:   u.Title,
		Type:    u.Type,
		Venue:   u.Venue,
		Date:    u.Date,
		Doi:     u.Doi,
		Url:     u.URL,
		Authors: u.Authors,
	}
}

func contentPbToOgp(p *contentv1.Ogp) *usecase.Ogp {
	if p == nil {
		return nil
	}
	return &usecase.Ogp{
		URL:         p.GetUrl(),
		Title:       p.GetTitle(),
		Description: p.GetDescription(),
		Images:      p.GetImages(),
		SiteName:    p.GetSiteName(),
		MediaType:   p.GetMediaType(),
		ContentType: p.GetContentType(),
		Favicons:    p.GetFavicons(),
	}
}

func contentOgpToPb(u *usecase.Ogp) *contentv1.Ogp {
	if u == nil {
		return nil
	}
	return &contentv1.Ogp{
		Url:         u.URL,
		Title:       u.Title,
		Description: u.Description,
		Images:      u.Images,
		SiteName:    u.SiteName,
		MediaType:   u.MediaType,
		ContentType: u.ContentType,
		Favicons:    u.Favicons,
	}
}
