// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type WorkLocation struct {
	Date     string `gorm:"column:date;primaryKey"`
	Location string `gorm:"column:location;not null"`
}

func (WorkLocation) TableName() string { return "workLocations" }

func NewWorkLocation(
	date string,
	location string,
) (*WorkLocation, error) {
	if date == "" {
		return nil, errors.New("date is required")
	}
	location = strings.TrimSpace(location)
	if location == "" {
		return nil, errors.New("location is required")
	}
	return &WorkLocation{
		Date:     date,
		Location: location,
	}, nil
}

var _ = time.Time{}

// @required / @email の文字列フィールドが無いエンティティでも import が使われるようにする
var _ = strings.TrimSpace
