// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"encoding/json"
{{- if .AnyReturnsEntity}}
	"errors"
{{- end}}
	"net/http"
{{- if .NeedsStrconv}}
	"strconv"
{{- end}}

{{- if .HandlerUsesEntity}}
	"{{.ImportEntity}}"
{{- end}}
{{- if .AnyReturnsEntity}}
	"{{.ImportRepository}}"
{{- end}}
	"{{.ImportUsecase}}"
)

type {{.HandlerTypeName}} struct {
	usecase usecase.{{.UsecaseTypeName}}
}

func New{{.HandlerTypeName}}(uc usecase.{{.UsecaseTypeName}}) *{{.HandlerTypeName}} {
	return &{{.HandlerTypeName}}{usecase: uc}
}

func (h *{{.HandlerTypeName}}) writeError(w http.ResponseWriter, err error) {
	status := http.StatusBadRequest
{{- range .UsedEntities}}
	if errors.Is(err, repository.Err{{.Name}}NotFound) {
		status = http.StatusNotFound
	}
	if errors.Is(err, repository.Err{{.Name}}AlreadyExists) {
		status = http.StatusConflict
	}
{{- end}}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
}
{{range .Methods}}
{{- if .Http}}
{{- if and .IsBodyMethod .HasBodyFields}}

type {{.Name}}Body struct {
{{- range .BodyFields}}
	{{.GoName}} {{.HandlerGoType}} `json:"{{.JsonName}}"`
{{- end}}
}
{{- end}}

// {{.Http.Method}} {{.Http.Path}}
func (h *{{$.HandlerTypeName}}) {{.Name}}(w http.ResponseWriter, r *http.Request) {
{{- if and .IsBodyMethod .HasBodyFields}}
	var body {{.Name}}Body
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
{{- end}}
{{- if and .IsQueryMethod .HasQueryFields}}
	_urlq := r.URL.Query()
{{- range .QueryFields}}
{{- if eq .QueryGoType "string"}}
	_{{.ParamName}} := _urlq.Get("{{.JsonName}}")
{{- else if eq .QueryGoType "int32"}}
	_{{.ParamName}}, _ := strconv.Atoi(_urlq.Get("{{.JsonName}}"))
{{- else if eq .QueryGoType "int64"}}
	_{{.ParamName}}, _ := strconv.ParseInt(_urlq.Get("{{.JsonName}}"), 10, 64)
{{- else if eq .QueryGoType "bool"}}
	_{{.ParamName}} := _urlq.Get("{{.JsonName}}") == "true"
{{- end}}
{{- end}}
{{- end}}
{{- if .ReturnsEntity}}
	result, err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- if .IsBodyMethod}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
{{- end}}
{{- if .IsQueryMethod}}
{{- range .QueryFields}}
{{- if eq .QueryGoType "string"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "int32"}}
		{{.GoName}}: int32(_{{.ParamName}}),
{{- else if eq .QueryGoType "int64"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "bool"}}
		{{.GoName}}: _{{.ParamName}},
{{- end}}
{{- end}}
{{- end}}
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.Err{{.EntityGoName}}NotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader({{if eq .Http.Method "POST"}}http.StatusCreated{{else}}http.StatusOK{{end}})
	_ = json.NewEncoder(w).Encode(result)
{{- else if .ReturnsList}}
	list, err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- if .IsBodyMethod}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
{{- end}}
{{- if .IsQueryMethod}}
{{- range .QueryFields}}
{{- if eq .QueryGoType "string"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "int32"}}
		{{.GoName}}: int32(_{{.ParamName}}),
{{- else if eq .QueryGoType "int64"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "bool"}}
		{{.GoName}}: _{{.ParamName}},
{{- end}}
{{- end}}
{{- end}}
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader({{if eq .Http.Method "POST"}}http.StatusCreated{{else}}http.StatusOK{{end}})
	_ = json.NewEncoder(w).Encode(list)
{{- else if .ReturnsOutput}}
	result, err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- if .IsBodyMethod}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
{{- end}}
{{- if .IsQueryMethod}}
{{- range .QueryFields}}
{{- if eq .QueryGoType "string"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "int32"}}
		{{.GoName}}: int32(_{{.ParamName}}),
{{- else if eq .QueryGoType "int64"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "bool"}}
		{{.GoName}}: _{{.ParamName}},
{{- end}}
{{- end}}
{{- end}}
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader({{if eq .Http.Method "POST"}}http.StatusCreated{{else}}http.StatusOK{{end}})
	_ = json.NewEncoder(w).Encode(result)
{{- else}}
	if err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- if .IsBodyMethod}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
{{- end}}
{{- if .IsQueryMethod}}
{{- range .QueryFields}}
{{- if eq .QueryGoType "string"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "int32"}}
		{{.GoName}}: int32(_{{.ParamName}}),
{{- else if eq .QueryGoType "int64"}}
		{{.GoName}}: _{{.ParamName}},
{{- else if eq .QueryGoType "bool"}}
		{{.GoName}}: _{{.ParamName}},
{{- end}}
{{- end}}
{{- end}}
	}); err != nil {
		h.writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
{{- end}}
}
{{- end}}
{{end}}
