// Code generated by mss-protoc-gen. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// MockSyncSettingRepository は repository.SyncSettingRepository のテスト用スタブ。
// 各 Func フィールドにスタブ関数を差し込み、未設定ならゼロ値を返す。
type MockSyncSettingRepository struct {
	SelectAllFunc  func(ctx context.Context) ([]*entity.SyncSetting, error)
	SelectByPKFunc func(ctx context.Context, id string) (*entity.SyncSetting, error)
	InsertFunc     func(ctx context.Context, syncSetting *entity.SyncSetting) error
	BulkInsertFunc func(ctx context.Context, syncSettings []*entity.SyncSetting) error
	UpsertFunc     func(ctx context.Context, syncSetting *entity.SyncSetting) error
	BulkUpsertFunc func(ctx context.Context, syncSettings []*entity.SyncSetting) error
	UpdateFunc     func(ctx context.Context, syncSetting *entity.SyncSetting) error
	DeleteFunc     func(ctx context.Context, id string) error
	BulkDeleteFunc func(ctx context.Context, ids []string) error
	DeleteAllFunc  func(ctx context.Context) error
}

var _ repository.SyncSettingRepository = (*MockSyncSettingRepository)(nil)

func (m *MockSyncSettingRepository) SelectAll(ctx context.Context) ([]*entity.SyncSetting, error) {
	if m.SelectAllFunc != nil {
		return m.SelectAllFunc(ctx)
	}
	return nil, nil
}

func (m *MockSyncSettingRepository) SelectByPK(ctx context.Context, id string) (*entity.SyncSetting, error) {
	if m.SelectByPKFunc != nil {
		return m.SelectByPKFunc(ctx, id)
	}
	return nil, nil
}

func (m *MockSyncSettingRepository) Insert(ctx context.Context, syncSetting *entity.SyncSetting) error {
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, syncSetting)
	}
	return nil
}

func (m *MockSyncSettingRepository) BulkInsert(ctx context.Context, syncSettings []*entity.SyncSetting) error {
	if m.BulkInsertFunc != nil {
		return m.BulkInsertFunc(ctx, syncSettings)
	}
	return nil
}

func (m *MockSyncSettingRepository) Upsert(ctx context.Context, syncSetting *entity.SyncSetting) error {
	if m.UpsertFunc != nil {
		return m.UpsertFunc(ctx, syncSetting)
	}
	return nil
}

func (m *MockSyncSettingRepository) BulkUpsert(ctx context.Context, syncSettings []*entity.SyncSetting) error {
	if m.BulkUpsertFunc != nil {
		return m.BulkUpsertFunc(ctx, syncSettings)
	}
	return nil
}

func (m *MockSyncSettingRepository) Update(ctx context.Context, syncSetting *entity.SyncSetting) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, syncSetting)
	}
	return nil
}

func (m *MockSyncSettingRepository) Delete(ctx context.Context, id string) error {
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, id)
	}
	return nil
}

func (m *MockSyncSettingRepository) BulkDelete(ctx context.Context, ids []string) error {
	if m.BulkDeleteFunc != nil {
		return m.BulkDeleteFunc(ctx, ids)
	}
	return nil
}

func (m *MockSyncSettingRepository) DeleteAll(ctx context.Context) error {
	if m.DeleteAllFunc != nil {
		return m.DeleteAllFunc(ctx)
	}
	return nil
}
