// Code generated by mss-protoc-gen. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// MockCalendarAccountRepository は repository.CalendarAccountRepository のテスト用スタブ。
// 各 Func フィールドにスタブ関数を差し込み、未設定ならゼロ値を返す。
type MockCalendarAccountRepository struct {
	SelectAllFunc  func(ctx context.Context) ([]*entity.CalendarAccount, error)
	SelectByPKFunc func(ctx context.Context, calendarId string) (*entity.CalendarAccount, error)
	InsertFunc     func(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	BulkInsertFunc func(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error
	UpsertFunc     func(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	BulkUpsertFunc func(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error
	UpdateFunc     func(ctx context.Context, calendarAccount *entity.CalendarAccount) error
	DeleteFunc     func(ctx context.Context, calendarId string) error
	BulkDeleteFunc func(ctx context.Context, calendarIds []string) error
	DeleteAllFunc  func(ctx context.Context) error
}

var _ repository.CalendarAccountRepository = (*MockCalendarAccountRepository)(nil)

func (m *MockCalendarAccountRepository) SelectAll(ctx context.Context) ([]*entity.CalendarAccount, error) {
	if m.SelectAllFunc != nil {
		return m.SelectAllFunc(ctx)
	}
	return nil, nil
}

func (m *MockCalendarAccountRepository) SelectByPK(ctx context.Context, calendarId string) (*entity.CalendarAccount, error) {
	if m.SelectByPKFunc != nil {
		return m.SelectByPKFunc(ctx, calendarId)
	}
	return nil, nil
}

func (m *MockCalendarAccountRepository) Insert(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, calendarAccount)
	}
	return nil
}

func (m *MockCalendarAccountRepository) BulkInsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error {
	if m.BulkInsertFunc != nil {
		return m.BulkInsertFunc(ctx, calendarAccounts)
	}
	return nil
}

func (m *MockCalendarAccountRepository) Upsert(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	if m.UpsertFunc != nil {
		return m.UpsertFunc(ctx, calendarAccount)
	}
	return nil
}

func (m *MockCalendarAccountRepository) BulkUpsert(ctx context.Context, calendarAccounts []*entity.CalendarAccount) error {
	if m.BulkUpsertFunc != nil {
		return m.BulkUpsertFunc(ctx, calendarAccounts)
	}
	return nil
}

func (m *MockCalendarAccountRepository) Update(ctx context.Context, calendarAccount *entity.CalendarAccount) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, calendarAccount)
	}
	return nil
}

func (m *MockCalendarAccountRepository) Delete(ctx context.Context, calendarId string) error {
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, calendarId)
	}
	return nil
}

func (m *MockCalendarAccountRepository) BulkDelete(ctx context.Context, calendarIds []string) error {
	if m.BulkDeleteFunc != nil {
		return m.BulkDeleteFunc(ctx, calendarIds)
	}
	return nil
}

func (m *MockCalendarAccountRepository) DeleteAll(ctx context.Context) error {
	if m.DeleteAllFunc != nil {
		return m.DeleteAllFunc(ctx)
	}
	return nil
}
