// Code generated by mss-protoc-gen. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/repository"
)

// MockSyncMirrorRepository は repository.SyncMirrorRepository のテスト用スタブ。
// 各 Func フィールドにスタブ関数を差し込み、未設定ならゼロ値を返す。
type MockSyncMirrorRepository struct {
	SelectAllFunc  func(ctx context.Context) ([]*entity.SyncMirror, error)
	SelectByPKFunc func(ctx context.Context, key string) (*entity.SyncMirror, error)
	InsertFunc     func(ctx context.Context, syncMirror *entity.SyncMirror) error
	BulkInsertFunc func(ctx context.Context, syncMirrors []*entity.SyncMirror) error
	UpsertFunc     func(ctx context.Context, syncMirror *entity.SyncMirror) error
	BulkUpsertFunc func(ctx context.Context, syncMirrors []*entity.SyncMirror) error
	UpdateFunc     func(ctx context.Context, syncMirror *entity.SyncMirror) error
	DeleteFunc     func(ctx context.Context, key string) error
	BulkDeleteFunc func(ctx context.Context, keys []string) error
	DeleteAllFunc  func(ctx context.Context) error
}

var _ repository.SyncMirrorRepository = (*MockSyncMirrorRepository)(nil)

func (m *MockSyncMirrorRepository) SelectAll(ctx context.Context) ([]*entity.SyncMirror, error) {
	if m.SelectAllFunc != nil {
		return m.SelectAllFunc(ctx)
	}
	return nil, nil
}

func (m *MockSyncMirrorRepository) SelectByPK(ctx context.Context, key string) (*entity.SyncMirror, error) {
	if m.SelectByPKFunc != nil {
		return m.SelectByPKFunc(ctx, key)
	}
	return nil, nil
}

func (m *MockSyncMirrorRepository) Insert(ctx context.Context, syncMirror *entity.SyncMirror) error {
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, syncMirror)
	}
	return nil
}

func (m *MockSyncMirrorRepository) BulkInsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error {
	if m.BulkInsertFunc != nil {
		return m.BulkInsertFunc(ctx, syncMirrors)
	}
	return nil
}

func (m *MockSyncMirrorRepository) Upsert(ctx context.Context, syncMirror *entity.SyncMirror) error {
	if m.UpsertFunc != nil {
		return m.UpsertFunc(ctx, syncMirror)
	}
	return nil
}

func (m *MockSyncMirrorRepository) BulkUpsert(ctx context.Context, syncMirrors []*entity.SyncMirror) error {
	if m.BulkUpsertFunc != nil {
		return m.BulkUpsertFunc(ctx, syncMirrors)
	}
	return nil
}

func (m *MockSyncMirrorRepository) Update(ctx context.Context, syncMirror *entity.SyncMirror) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, syncMirror)
	}
	return nil
}

func (m *MockSyncMirrorRepository) Delete(ctx context.Context, key string) error {
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, key)
	}
	return nil
}

func (m *MockSyncMirrorRepository) BulkDelete(ctx context.Context, keys []string) error {
	if m.BulkDeleteFunc != nil {
		return m.BulkDeleteFunc(ctx, keys)
	}
	return nil
}

func (m *MockSyncMirrorRepository) DeleteAll(ctx context.Context) error {
	if m.DeleteAllFunc != nil {
		return m.DeleteAllFunc(ctx)
	}
	return nil
}
