// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"connectrpc.com/connect"

	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/worklocation/v1/worklocationv1connect"

	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/handler"
	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/usecase"
)

// Handlers はこのコンテキストの Connect Handler を束ねた DI コンテナ。
type Handlers struct {
	WorkLocationService *handler.WorkLocationHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	workLocationUsecase usecase.WorkLocationUsecase,
) *Handlers {
	return &Handlers{
		WorkLocationService: handler.NewWorkLocationHandler(workLocationUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する。opts には interceptor（認可・ログ）を渡す。
func (h *Handlers) Register(mux *http.ServeMux, opts ...connect.HandlerOption) {
	mux.Handle(worklocationv1connect.NewWorkLocationServiceHandler(h.WorkLocationService, opts...))
}
