// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type CalendarAccount struct {
	CalendarID   string    `gorm:"column:calendar_id;primaryKey"`
	RefreshToken string    `gorm:"column:refresh_token;not null"`
	Private      bool      `gorm:"column:private;not null"`
	ConnectedAt  time.Time `gorm:"column:connected_at;not null"`
	ColorID      string    `gorm:"column:color_id;not null"`
}

func (CalendarAccount) TableName() string { return "calendarAccounts" }

func NewCalendarAccount(
	calendarId string,
	refreshToken string,
	private bool,
	connectedAt time.Time,
	colorId string,
) (*CalendarAccount, error) {
	if calendarId == "" {
		return nil, errors.New("calendar_id is required")
	}
	refreshToken = strings.TrimSpace(refreshToken)
	if refreshToken == "" {
		return nil, errors.New("refresh_token is required")
	}
	return &CalendarAccount{
		CalendarID:   calendarId,
		RefreshToken: refreshToken,
		Private:      private,
		ConnectedAt:  connectedAt,
		ColorID:      colorId,
	}, nil
}

var _ = time.Time{}

// @required / @email の文字列フィールドが無いエンティティでも import が使われるようにする
var _ = strings.TrimSpace
