// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type SyncSetting struct {
	ID     string `gorm:"column:id;primaryKey"`
	Master string `gorm:"column:master;not null"`
}

func (SyncSetting) TableName() string { return "syncSettings" }

func NewSyncSetting(
	id string,
	master string,
) (*SyncSetting, error) {
	if id == "" {
		return nil, errors.New("id is required")
	}
	return &SyncSetting{
		ID:     id,
		Master: master,
	}, nil
}

var _ = time.Time{}

// @required / @email の文字列フィールドが無いエンティティでも import が使われるようにする
var _ = strings.TrimSpace
