// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type SyncMirror struct {
	Key    string `gorm:"column:key;primaryKey"`
	Digest string `gorm:"column:digest;not null"`
	EndAt  string `gorm:"column:end_at;not null"`
}

func (SyncMirror) TableName() string { return "syncMirrors" }

func NewSyncMirror(
	key string,
	digest string,
	endAt string,
) (*SyncMirror, error) {
	if key == "" {
		return nil, errors.New("key is required")
	}
	return &SyncMirror{
		Key:    key,
		Digest: digest,
		EndAt:  endAt,
	}, nil
}

var _ = time.Time{}

// @required / @email の文字列フィールドが無いエンティティでも import が使われるようにする
var _ = strings.TrimSpace
