// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type ListQiitaItemsInput struct {
	Page        int32
	Initial     bool
	IncludeTags bool
	PerPage     int32
}

type ScrapeQiitaProfileInput struct{}

type ScrapeQiitaArticleLinksInput struct {
	URL string
}

type ListConnpassEventsInput struct {
	Nickname string
}

type ListOrcidWorksInput struct{}

type GetOgpInput struct {
	Urls    []string
	NoCache bool
}

type ListQiitaItemsOutput struct {
	Urls  []string     `json:"urls"`
	Items []*QiitaItem `json:"items"`
}

type ScrapeQiitaProfileOutput struct {
	PickupArticles []*ScrapedArticle `json:"pickup_articles"`
	LatestArticles []*ScrapedArticle `json:"latest_articles"`
}

type ScrapeQiitaArticleLinksOutput struct {
	Links []*ArticleLink `json:"links"`
}

type ListConnpassEventsOutput struct {
	ResultsReturned  int32            `json:"results_returned"`
	ResultsAvailable int32            `json:"results_available"`
	ResultsStart     int32            `json:"results_start"`
	Events           []*ConnpassEvent `json:"events"`
}

type ListOrcidWorksOutput struct {
	OrcidID string       `json:"orcid_id"`
	Works   []*OrcidWork `json:"works"`
}

type GetOgpOutput struct {
	Data []*Ogp `json:"data"`
}

type ArticleLink struct {
	URL   string `json:"url"`
	Title string `json:"title"`
}

type ConnpassEvent struct {
	EventID   int64  `json:"event_id"`
	Title     string `json:"title"`
	Catch     string `json:"catch"`
	EventURL  string `json:"event_url"`
	StartedAt string `json:"started_at"`
	EndedAt   string `json:"ended_at"`
	Limit     int32  `json:"limit"`
	Accepted  int32  `json:"accepted"`
	Waiting   int32  `json:"waiting"`
	Place     string `json:"place"`
	Address   string `json:"address"`
	ImageURL  string `json:"image_url"`
}

type Ogp struct {
	URL         string   `json:"url"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Images      []string `json:"images"`
	SiteName    string   `json:"site_name"`
	MediaType   string   `json:"media_type"`
	ContentType string   `json:"content_type"`
	Favicons    []string `json:"favicons"`
}

type OrcidWork struct {
	PutCode int64    `json:"put_code"`
	Title   string   `json:"title"`
	Type    string   `json:"type"`
	Venue   string   `json:"venue"`
	Date    string   `json:"date"`
	Doi     string   `json:"doi"`
	URL     string   `json:"url"`
	Authors []string `json:"authors"`
}

type QiitaItem struct {
	URL   string      `json:"url"`
	Title string      `json:"title"`
	Body  string      `json:"body"`
	Tags  []*QiitaTag `json:"tags"`
}

type QiitaTag struct {
	Name     string   `json:"name"`
	Versions []string `json:"versions"`
}

type ScrapedArticle struct {
	URL   string   `json:"url"`
	Title string   `json:"title"`
	Tags  []string `json:"tags"`
}

// ContentUsecase は ContentService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type ContentUsecase interface {
	ListQiitaItems(ctx context.Context, input ListQiitaItemsInput) (*ListQiitaItemsOutput, error)
	ScrapeQiitaProfile(ctx context.Context, input ScrapeQiitaProfileInput) (*ScrapeQiitaProfileOutput, error)
	ScrapeQiitaArticleLinks(ctx context.Context, input ScrapeQiitaArticleLinksInput) (*ScrapeQiitaArticleLinksOutput, error)
	ListConnpassEvents(ctx context.Context, input ListConnpassEventsInput) (*ListConnpassEventsOutput, error)
	ListOrcidWorks(ctx context.Context, input ListOrcidWorksInput) (*ListOrcidWorksOutput, error)
	GetOgp(ctx context.Context, input GetOgpInput) (*GetOgpOutput, error)
}
