// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/repository"
)

// Redis への保存形式（docs/patterns/infra-swap.md: string に JSON エンコード）。
// 本体は workLocations:rec:<pk>、@unique の副次インデックスは workLocations:idx:<field>:<value> → pk。
type redisWorkLocationRecord struct {
	Date     string `json:"date"`
	Location string `json:"location"`
}

func toWorkLocationRecord(e *entity.WorkLocation) redisWorkLocationRecord {
	return redisWorkLocationRecord{
		Date:     e.Date,
		Location: e.Location,
	}
}

func (r redisWorkLocationRecord) toEntity() *entity.WorkLocation {
	return &entity.WorkLocation{
		Date:     r.Date,
		Location: r.Location,
	}
}

type redisWorkLocationRepository struct {
	client redis.UniversalClient
}

func NewRedisWorkLocationRepository(client redis.UniversalClient) repository.WorkLocationRepository {
	return &redisWorkLocationRepository{client: client}
}

var _ repository.WorkLocationRepository = (*redisWorkLocationRepository)(nil)
var _ = time.Time{}

const workLocationKeyPrefix = "workLocations:rec:"

func workLocationKey(pk string) string { return workLocationKeyPrefix + fmt.Sprint(pk) }

func workLocationIndexKeys(e *entity.WorkLocation) []string {
	return []string{}
}

func (r *redisWorkLocationRepository) get(ctx context.Context, key string) (*entity.WorkLocation, error) {
	raw, err := r.client.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rec redisWorkLocationRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("decode %s: %w", key, err)
	}
	return rec.toEntity(), nil
}

func (r *redisWorkLocationRepository) SelectAll(ctx context.Context) ([]*entity.WorkLocation, error) {
	var keys []string
	iter := r.client.Scan(ctx, 0, workLocationKeyPrefix+"*", 500).Iterator()
	for iter.Next(ctx) {
		keys = append(keys, iter.Val())
	}
	if err := iter.Err(); err != nil {
		return nil, err
	}
	out := make([]*entity.WorkLocation, 0, len(keys))
	for start := 0; start < len(keys); start += 500 {
		end := min(start+500, len(keys))
		vals, err := r.client.MGet(ctx, keys[start:end]...).Result()
		if err != nil {
			return nil, err
		}
		for i, v := range vals {
			s, ok := v.(string)
			if !ok {
				continue // SCAN と MGET の間に消えた
			}
			var rec redisWorkLocationRecord
			if err := json.Unmarshal([]byte(s), &rec); err != nil {
				return nil, fmt.Errorf("decode %s: %w", keys[start+i], err)
			}
			out = append(out, rec.toEntity())
		}
	}
	return out, nil
}

func (r *redisWorkLocationRepository) SelectByPK(ctx context.Context, date string) (*entity.WorkLocation, error) {
	return r.get(ctx, workLocationKey(date))
}

func (r *redisWorkLocationRepository) Insert(ctx context.Context, workLocation *entity.WorkLocation) error {
	raw, err := json.Marshal(toWorkLocationRecord(workLocation))
	if err != nil {
		return err
	}
	key := workLocationKey(workLocation.Date)
	ok, err := r.client.SetNX(ctx, key, raw, 0).Result()
	if err != nil {
		return err
	}
	if !ok {
		return repository.ErrWorkLocationAlreadyExists
	}
	pk := fmt.Sprint(workLocation.Date)
	var claimed []string
	for _, idx := range workLocationIndexKeys(workLocation) {
		ok, err := r.client.SetNX(ctx, idx, pk, 0).Result()
		if err != nil || !ok {
			// 一意制約違反: 先に書いた分を戻す
			r.client.Del(ctx, append(claimed, key)...)
			if err != nil {
				return err
			}
			return repository.ErrWorkLocationAlreadyExists
		}
		claimed = append(claimed, idx)
	}
	return nil
}

func (r *redisWorkLocationRepository) BulkInsert(ctx context.Context, workLocations []*entity.WorkLocation) error {
	for _, e := range workLocations {
		if err := r.Insert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisWorkLocationRepository) Upsert(ctx context.Context, workLocation *entity.WorkLocation) error {
	prev, err := r.SelectByPK(ctx, workLocation.Date)
	if err != nil {
		return err
	}
	raw, err := json.Marshal(toWorkLocationRecord(workLocation))
	if err != nil {
		return err
	}
	pk := fmt.Sprint(workLocation.Date)
	pipe := r.client.TxPipeline()
	if prev != nil {
		for _, idx := range workLocationIndexKeys(prev) {
			pipe.Del(ctx, idx)
		}
	}
	pipe.Set(ctx, workLocationKey(workLocation.Date), raw, 0)
	for _, idx := range workLocationIndexKeys(workLocation) {
		pipe.Set(ctx, idx, pk, 0)
	}
	_, err = pipe.Exec(ctx)
	return err
}

func (r *redisWorkLocationRepository) BulkUpsert(ctx context.Context, workLocations []*entity.WorkLocation) error {
	for _, e := range workLocations {
		if err := r.Upsert(ctx, e); err != nil {
			return err
		}
	}
	return nil
}

func (r *redisWorkLocationRepository) Update(ctx context.Context, workLocation *entity.WorkLocation) error {
	n, err := r.client.Exists(ctx, workLocationKey(workLocation.Date)).Result()
	if err != nil {
		return err
	}
	if n == 0 {
		return repository.ErrWorkLocationNotFound
	}
	return r.Upsert(ctx, workLocation)
}

func (r *redisWorkLocationRepository) Delete(ctx context.Context, date string) error {
	prev, err := r.SelectByPK(ctx, date)
	if err != nil {
		return err
	}
	if prev == nil {
		return repository.ErrWorkLocationNotFound
	}
	return r.client.Del(ctx, append(workLocationIndexKeys(prev), workLocationKey(date))...).Err()
}

func (r *redisWorkLocationRepository) BulkDelete(ctx context.Context, dates []string) error {
	missing := false
	for _, pk := range dates {
		if err := r.Delete(ctx, pk); err != nil {
			if errors.Is(err, repository.ErrWorkLocationNotFound) {
				missing = true
				continue
			}
			return err
		}
	}
	if missing {
		return repository.ErrWorkLocationNotFound
	}
	return nil
}

func (r *redisWorkLocationRepository) DeleteAll(ctx context.Context) error {
	for _, pattern := range []string{workLocationKeyPrefix + "*", "workLocations:idx:*"} {
		iter := r.client.Scan(ctx, 0, pattern, 500).Iterator()
		var keys []string
		for iter.Next(ctx) {
			keys = append(keys, iter.Val())
		}
		if err := iter.Err(); err != nil {
			return err
		}
		if len(keys) > 0 {
			if err := r.client.Del(ctx, keys...).Err(); err != nil {
				return err
			}
		}
	}
	return nil
}

var _ = sort.Strings
