// Code generated by mss-protoc-gen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

// CalendarAccountDTO は CalendarAccount エンティティをクライアントへ返すための JSON シリアライズ型。
// json タグはここで一元管理する。entity 側は GORM タグのみ持つ。
type CalendarAccountDTO struct {
	CalendarID      string `json:"calendar_id"`
	RefreshToken    string `json:"refresh_token"`
	Private         bool   `json:"private"`
	ConnectedAtUnix int64  `json:"connected_at_unix"`
}

// FromCalendarAccount は entity.CalendarAccount を CalendarAccountDTO に変換する。
// nil を渡したら nil を返す。
func FromCalendarAccount(e *entity.CalendarAccount) *CalendarAccountDTO {
	if e == nil {
		return nil
	}
	return &CalendarAccountDTO{
		CalendarID:      e.CalendarID,
		RefreshToken:    e.RefreshToken,
		Private:         e.Private,
		ConnectedAtUnix: e.ConnectedAt.Unix(),
	}
}

// FromCalendarAccounts は []*entity.CalendarAccount を []*CalendarAccountDTO に変換する。
func FromCalendarAccounts(es []*entity.CalendarAccount) []*CalendarAccountDTO {
	out := make([]*CalendarAccountDTO, 0, len(es))
	for _, e := range es {
		out = append(out, FromCalendarAccount(e))
	}
	return out
}

var _ = time.Time{}
