// Code generated by mss-protoc-gen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

// SyncSettingDTO は SyncSetting エンティティをクライアントへ返すための JSON シリアライズ型。
// json タグはここで一元管理する。entity 側は GORM タグのみ持つ。
type SyncSettingDTO struct {
	ID     string `json:"id"`
	Master string `json:"master"`
}

// FromSyncSetting は entity.SyncSetting を SyncSettingDTO に変換する。
// nil を渡したら nil を返す。
func FromSyncSetting(e *entity.SyncSetting) *SyncSettingDTO {
	if e == nil {
		return nil
	}
	return &SyncSettingDTO{
		ID:     e.ID,
		Master: e.Master,
	}
}

// FromSyncSettings は []*entity.SyncSetting を []*SyncSettingDTO に変換する。
func FromSyncSettings(es []*entity.SyncSetting) []*SyncSettingDTO {
	out := make([]*SyncSettingDTO, 0, len(es))
	for _, e := range es {
		out = append(out, FromSyncSetting(e))
	}
	return out
}

var _ = time.Time{}
