// Code generated by mss-protoc-gen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/javalangruntimeexception/taramanji/backend/internal/calendarsync/domain/entity"
)

// SyncMirrorDTO は SyncMirror エンティティをクライアントへ返すための JSON シリアライズ型。
// json タグはここで一元管理する。entity 側は GORM タグのみ持つ。
type SyncMirrorDTO struct {
	Key    string `json:"key"`
	Digest string `json:"digest"`
	EndAt  string `json:"end_at"`
}

// FromSyncMirror は entity.SyncMirror を SyncMirrorDTO に変換する。
// nil を渡したら nil を返す。
func FromSyncMirror(e *entity.SyncMirror) *SyncMirrorDTO {
	if e == nil {
		return nil
	}
	return &SyncMirrorDTO{
		Key:    e.Key,
		Digest: e.Digest,
		EndAt:  e.EndAt,
	}
}

// FromSyncMirrors は []*entity.SyncMirror を []*SyncMirrorDTO に変換する。
func FromSyncMirrors(es []*entity.SyncMirror) []*SyncMirrorDTO {
	out := make([]*SyncMirrorDTO, 0, len(es))
	for _, e := range es {
		out = append(out, FromSyncMirror(e))
	}
	return out
}

var _ = time.Time{}
