// Code generated by mss-protoc-gen. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/entity"
	"github.com/javalangruntimeexception/taramanji/backend/internal/worklocation/domain/repository"
)

// MockWorkLocationRepository は repository.WorkLocationRepository のテスト用スタブ。
// 各 Func フィールドにスタブ関数を差し込み、未設定ならゼロ値を返す。
type MockWorkLocationRepository struct {
	SelectAllFunc  func(ctx context.Context) ([]*entity.WorkLocation, error)
	SelectByPKFunc func(ctx context.Context, date string) (*entity.WorkLocation, error)
	InsertFunc     func(ctx context.Context, workLocation *entity.WorkLocation) error
	BulkInsertFunc func(ctx context.Context, workLocations []*entity.WorkLocation) error
	UpsertFunc     func(ctx context.Context, workLocation *entity.WorkLocation) error
	BulkUpsertFunc func(ctx context.Context, workLocations []*entity.WorkLocation) error
	UpdateFunc     func(ctx context.Context, workLocation *entity.WorkLocation) error
	DeleteFunc     func(ctx context.Context, date string) error
	BulkDeleteFunc func(ctx context.Context, dates []string) error
	DeleteAllFunc  func(ctx context.Context) error
}

var _ repository.WorkLocationRepository = (*MockWorkLocationRepository)(nil)

func (m *MockWorkLocationRepository) SelectAll(ctx context.Context) ([]*entity.WorkLocation, error) {
	if m.SelectAllFunc != nil {
		return m.SelectAllFunc(ctx)
	}
	return nil, nil
}

func (m *MockWorkLocationRepository) SelectByPK(ctx context.Context, date string) (*entity.WorkLocation, error) {
	if m.SelectByPKFunc != nil {
		return m.SelectByPKFunc(ctx, date)
	}
	return nil, nil
}

func (m *MockWorkLocationRepository) Insert(ctx context.Context, workLocation *entity.WorkLocation) error {
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, workLocation)
	}
	return nil
}

func (m *MockWorkLocationRepository) BulkInsert(ctx context.Context, workLocations []*entity.WorkLocation) error {
	if m.BulkInsertFunc != nil {
		return m.BulkInsertFunc(ctx, workLocations)
	}
	return nil
}

func (m *MockWorkLocationRepository) Upsert(ctx context.Context, workLocation *entity.WorkLocation) error {
	if m.UpsertFunc != nil {
		return m.UpsertFunc(ctx, workLocation)
	}
	return nil
}

func (m *MockWorkLocationRepository) BulkUpsert(ctx context.Context, workLocations []*entity.WorkLocation) error {
	if m.BulkUpsertFunc != nil {
		return m.BulkUpsertFunc(ctx, workLocations)
	}
	return nil
}

func (m *MockWorkLocationRepository) Update(ctx context.Context, workLocation *entity.WorkLocation) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, workLocation)
	}
	return nil
}

func (m *MockWorkLocationRepository) Delete(ctx context.Context, date string) error {
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, date)
	}
	return nil
}

func (m *MockWorkLocationRepository) BulkDelete(ctx context.Context, dates []string) error {
	if m.BulkDeleteFunc != nil {
		return m.BulkDeleteFunc(ctx, dates)
	}
	return nil
}

func (m *MockWorkLocationRepository) DeleteAll(ctx context.Context) error {
	if m.DeleteAllFunc != nil {
		return m.DeleteAllFunc(ctx)
	}
	return nil
}
