// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"{{.ImportEntity}}"
	"{{.ImportRepository}}"
	"{{.ImportTx}}"
)

type postgres{{.Name}}Repository struct{}

func NewPostgres{{.Name}}Repository() repository.{{.Name}}Repository {
	return &postgres{{.Name}}Repository{}
}

// AutoMigrate{{.Name}} は開発用途のスキーマ同期ヘルパー。
// 本番では Goose / Atlas / Flyway 等のマイグレーションツールを使うこと。
func AutoMigrate{{.Name}}(db *gorm.DB) error {
	return db.AutoMigrate(&entity.{{.Name}}{})
}

var _ repository.{{.Name}}Repository = (*postgres{{.Name}}Repository)(nil)
var _ = time.Time{}

func (r *postgres{{.Name}}Repository) SelectAll(ctx context.Context) ([]*entity.{{.Name}}, error) {
	var out []*entity.{{.Name}}
	if err := tx.From(ctx).WithContext(ctx).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

func (r *postgres{{.Name}}Repository) SelectByPK(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) (*entity.{{.Name}}, error) {
	var e entity.{{.Name}}
	err := tx.From(ctx).WithContext(ctx).Where("{{.PKField.SnakeName}} = ?", {{.PKField.ParamName}}).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}
{{range .UniqueFieldsNonPK}}
func (r *postgres{{$.Name}}Repository) SelectBy{{.GoName}}(ctx context.Context, {{.ParamName}} {{.GoType}}) (*entity.{{$.Name}}, error) {
	var e entity.{{$.Name}}
	err := tx.From(ctx).WithContext(ctx).Where("{{.SnakeName}} = ?", {{.ParamName}}).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}
{{end}}
func (r *postgres{{.Name}}Repository) Insert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	if err := tx.From(ctx).WithContext(ctx).Create({{.LowerFirst}}).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.Err{{.Name}}AlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgres{{.Name}}Repository) BulkInsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	if len({{.Plural}}) == 0 {
		return nil
	}
	if err := tx.From(ctx).WithContext(ctx).CreateInBatches({{.Plural}}, 100).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.Err{{.Name}}AlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgres{{.Name}}Repository) Upsert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	return tx.From(ctx).WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create({{.LowerFirst}}).Error
}

func (r *postgres{{.Name}}Repository) BulkUpsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	if len({{.Plural}}) == 0 {
		return nil
	}
	return tx.From(ctx).WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches({{.Plural}}, 100).Error
}

func (r *postgres{{.Name}}Repository) Update(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	res := tx.From(ctx).WithContext(ctx).Model(&entity.{{.Name}}{}).Where("{{.PKField.SnakeName}} = ?", {{.LowerFirst}}.{{.PKField.GoName}}).Updates({{.LowerFirst}})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *postgres{{.Name}}Repository) Delete(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) error {
	res := tx.From(ctx).WithContext(ctx).Where("{{.PKField.SnakeName}} = ?", {{.PKField.ParamName}}).Delete(&entity.{{.Name}}{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *postgres{{.Name}}Repository) BulkDelete(ctx context.Context, {{.PKField.ParamName}}s []{{.PKField.GoType}}) error {
	if len({{.PKField.ParamName}}s) == 0 {
		return nil
	}
	res := tx.From(ctx).WithContext(ctx).Where("{{.PKField.SnakeName}} IN ?", {{.PKField.ParamName}}s).Delete(&entity.{{.Name}}{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected != int64(len({{.PKField.ParamName}}s)) {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *postgres{{.Name}}Repository) DeleteAll(ctx context.Context) error {
	return tx.From(ctx).WithContext(ctx).Where("1 = 1").Delete(&entity.{{.Name}}{}).Error
}
{{- if .PagingField}}

func (r *postgres{{.Name}}Repository) SelectByCursor(ctx context.Context, limit int, after *{{.PagingField.GoType}}) ([]*entity.{{.Name}}, error) {
	q := tx.From(ctx).WithContext(ctx).Order("{{.PagingField.SnakeName}} ASC").Limit(limit)
	if after != nil {
		q = q.Where("{{.PagingField.SnakeName}} > ?", *after)
	}
	var out []*entity.{{.Name}}
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
{{- end}}
