// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type GetStatusInput struct{}

type RunSyncInput struct{}

type UpdateSettingsInput struct {
	SetMaster         bool
	Master            string
	PrivateCalendarID string
	PrivateValue      bool
	ColorCalendarID   string
	ColorID           string
}

type DisconnectInput struct {
	CalendarID string
}

type GetStatusOutput struct {
	Master   string         `json:"master"`
	Accounts []*AccountView `json:"accounts"`
	LastRun  *LastRun       `json:"last_run"`
}

type RunSyncOutput struct {
	Run     *LastRun `json:"run"`
	Skipped bool     `json:"skipped"`
}

type DisconnectOutput struct {
	Deleted int32 `json:"deleted"`
	Failed  int32 `json:"failed"`
}

type AccountView struct {
	CalendarID  string `json:"calendar_id"`
	Private     bool   `json:"private"`
	ConnectedAt string `json:"connected_at"`
	ColorID     string `json:"color_id"`
}

type LastRun struct {
	SourceEvents int32        `json:"source_events"`
	Mirrors      int32        `json:"mirrors"`
	Writes       int32        `json:"writes"`
	Deletes      int32        `json:"deletes"`
	Pending      int32        `json:"pending"`
	Errors       []*SyncError `json:"errors"`
	At           string       `json:"at"`
	DurationMs   int64        `json:"duration_ms"`
	Reconnect    []string     `json:"reconnect"`
}

type SyncError struct {
	CalendarID string `json:"calendar_id"`
	Error      string `json:"error"`
}

// CalendarSyncUsecase は CalendarSyncService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type CalendarSyncUsecase interface {
	GetStatus(ctx context.Context, input GetStatusInput) (*GetStatusOutput, error)
	RunSync(ctx context.Context, input RunSyncInput) (*RunSyncOutput, error)
	UpdateSettings(ctx context.Context, input UpdateSettingsInput) error
	Disconnect(ctx context.Context, input DisconnectInput) (*DisconnectOutput, error)
}
