// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
)

type GetSessionInput struct{}

type GetSessionOutput struct {
	User *User `json:"user"`
}

type User struct {
	Email   string `json:"email"`
	Name    string `json:"name"`
	Picture string `json:"picture"`
}

// IdentityUsecase は IdentityService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type IdentityUsecase interface {
	GetSession(ctx context.Context, input GetSessionInput) (*GetSessionOutput, error)
}
