// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"context"

	"connectrpc.com/connect"

	identityv1 "github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/identity/v1"
	"github.com/javalangruntimeexception/taramanji/backend/gen/taramanji/identity/v1/identityv1connect"
	"github.com/javalangruntimeexception/taramanji/backend/internal/identity/usecase"
	"github.com/javalangruntimeexception/taramanji/backend/pkg/util/errs"
)

// IdentityHandler は IdentityService の Connect ハンドラ。
// 1 実装で Connect / gRPC / gRPC-Web を受ける。業務エラーは errs.ToConnect で Connect のエラーに変換する。
type IdentityHandler struct {
	usecase usecase.IdentityUsecase
}

func NewIdentityHandler(uc usecase.IdentityUsecase) *IdentityHandler {
	return &IdentityHandler{usecase: uc}
}

var _ identityv1connect.IdentityServiceHandler = (*IdentityHandler)(nil)

func (h *IdentityHandler) GetSession(ctx context.Context, req *connect.Request[identityv1.GetSessionRequest]) (*connect.Response[identityv1.GetSessionResponse], error) {
	out, err := h.usecase.GetSession(ctx, usecase.GetSessionInput{})
	if err != nil {
		return nil, errs.ToConnect(ctx, err)
	}
	return connect.NewResponse(&identityv1.GetSessionResponse{User: identityUserToPb(out.User)}), nil
}

func identityPbToUser(p *identityv1.User) *usecase.User {
	if p == nil {
		return nil
	}
	return &usecase.User{
		Email:   p.GetEmail(),
		Name:    p.GetName(),
		Picture: p.GetPicture(),
	}
}

func identityUserToPb(u *usecase.User) *identityv1.User {
	if u == nil {
		return nil
	}
	return &identityv1.User{
		Email:   u.Email,
		Name:    u.Name,
		Picture: u.Picture,
	}
}
